### ISSUE TITLE
stable `removeLike` causes the program to crash

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#106]
### Steps to reproduce

1. Call remove `youtube.interact.removeLike` with a video ID of a liked video.
2. Observe the bug.

### Failure Logs

```shell
Server error:  /home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/core/InteractionManager.js:46
    const action = await this.actions.engage('like/removelike', { video_id });
                                      ^

TypeError: Cannot read properties of undefined (reading 'engage')
    at InteractionManager.removeLike (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/core/InteractionManager.js:46:39)
    at WebSocket.<anonymous> (file:///home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/index.js:251:38)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/ws/lib/websocket.js:1169:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:390:12)

Node.js v17.9.0
```

### Expected behavior

The like to be removed.

### Current behavior

A crash.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by Wykerd** [comment]
This issue is already fixed on the main branch, property `actions` should've been `#actions`


https://github.com/LuanRT/YouTube.js/blob/fb68e6bcfedecc67e9131b71292a2dd3a21b7f14/lib/core/InteractionManager.ts#L30
