### ISSUE TITLE
res.redirect error

### ISSUE THREAD

**Issue by devcycode** [LuanRT/YouTube.js#124]
### Question

Hello guys I get an error while doing res.cookie and res.redirect in the success message.

My Code:
```
const loginPageShow = async (req, res, next) => {

    try {
        const youtube = await new Innertube();

        var creds = '';


        youtube.ev.on('auth', (data) => {

            if (data.status == 'AUTHORIZATION_PENDING') {

                res.render('user/Login', { layout: '../layouts/General', title: `Youtube Abone Hilesi`, description: ``, keywords: ``, data })

            } else if (data.status == 'SUCCESS') {
                

                function credsSend() {

                    return creds = data.credentials;
                }
                credsSend()

                         const datax = {
                             time: Date(),
                             userId: data.credentials.access_token,
                         }
                         const jwtToken = jwt.sign(datax, process.env.JWT_SECRET_KEY, { expiresIn: '1d' });
             
                         res.clearCookie('access_token');
             
                         res.cookie('access_token', jwtToken, { expires: new Date(Date.now() + 900000) })
                         //console.log(req.cookies.access_token);
                         res.redirect(`https://twitter.com`);

            }

        });


        await youtube.signIn(creds);


       async function check() {

            const uyeVarMiFilter = { channel_id: (await youtube.account.getInfo()).channel_id };
            const uyeVarMi = await User.find(uyeVarMiFilter).countDocuments();
            if (uyeVarMi > 0) {
                //const delUser = await User.findOneAndDelete({ channel_id: (await youtube.account.getInfo()).channel_id })
                const guncelBilgiler = {
                    name: (await youtube.account.getInfo()).name,
                    email: (await youtube.account.getInfo()).email,
                    channel_id: (await youtube.account.getInfo()).channel_id,
                    subscriber_count: (await youtube.account.getInfo()).subscriber_count,
                    photo: (await youtube.account.getInfo()).photo[0].url,
                    access_token: creds.access_token,
                    refresh_token: creds.refresh_token,
                    expires: creds.expires,
                }
                await User.findOneAndUpdate(uyeVarMiFilter, guncelBilgiler)
            } else {
                const filter = { access_token: creds.access_token };

                const newUser = new User({
                    name: (await youtube.account.getInfo()).name,
                    email: (await youtube.account.getInfo()).email,
                    channel_id: (await youtube.account.getInfo()).channel_id,
                    subscriber_count: (await youtube.account.getInfo()).subscriber_count,
                    photo: (await youtube.account.getInfo()).photo[0].url,
                    access_token: creds.access_token,
                    refresh_token: creds.refresh_token,
                    expires: creds.expires,
                    tActive: '1'
                });
                await newUser.save();
            }
        } check(); 

    } catch (error) {
        console.log(error);
    }



}
```

Error Code:

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/Users/canyesilyurt/Desktop/ytPanel/node_modules/express/lib/response.js:794:10)
    at ServerResponse.append (/Users/canyesilyurt/Desktop/ytPanel/node_modules/express/lib/response.js:755:15)
    at ServerResponse.res.cookie (/Users/canyesilyurt/Desktop/ytPanel/node_modules/express/lib/response.js:884:8)
    at ServerResponse.clearCookie (/Users/canyesilyurt/Desktop/ytPanel/node_modules/express/lib/response.js:827:15)
    at EventEmitter.<anonymous> (/Users/canyesilyurt/Desktop/ytPanel/src/controllers/homeController.js:45:30)
    at EventEmitter.emit (node:events:532:35)
    at Timeout._onTimeout (/Users/canyesilyurt/Desktop/ytPanel/node_modules/youtubei.js/lib/core/OAuth.js:120:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
[nodemon] app crashed - waiting for file changes before starting...
```

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by Wykerd** [comment]
This error appears to be unrelated to YouTube.js and rather an error in your Express.js logic.

**Comment by MasterOfBob777** [comment]
(Also just a little tip, refactoring your `getInfo()` calls into a single variable will most likely improve your performance drastically and might even help some issues you might encounter down the line, because each call does a network request)

**Comment by devcycode** [comment]
> This error appears to be unrelated to YouTube.js and rather an error in your Express.js logic.

When I checked, it should redirect in the success loop but it doesn't. The problem goes away when I don't use res.render in the AUTHORIZATION_PENDING loop, but if I remove the res.render command, I have no idea how to show the code to the user.

**Comment by Wykerd** [comment]
> When I checked, it should redirect in the success loop but it doesn't. The problem goes away when I don't use res.render in the AUTHORIZATION_PENDING loop, but if I remove the res.render command, I have no idea how to show the code to the user.

You cannot send a page to the user (in the AUTHORIZATION_PENDING callback) and then update the headers afterwards, HTTP doesn't allow this as the body in sent after the headers (which contain both the cookies and redirect location). 

The best way will be to use clientside javascript to handle this.

**Comment by devcycode** [comment]
> > When I checked, it should redirect in the success loop but it doesn't. The problem goes away when I don't use res.render in the AUTHORIZATION_PENDING loop, but if I remove the res.render command, I have no idea how to show the code to the user.
> 
> You cannot send a page to the user (in the AUTHORIZATION_PENDING callback) and then update the headers afterwards, HTTP doesn't allow this as the body in sent after the headers (which contain both the cookies and redirect location).
> 
> The best way will be to use clientside javascript to handle this.

How do I do this, can you show a source?

```
youtube.ev.on('auth', (data) => {
      switch (data.status) {
        case 'AUTHORIZATION_PENDING':
          console.log(`
                Hello! On your phone or computer,
                go to ${data.verification_url} and enter
                the code ${data.code}.
              `);
              next();
          break;

          case 'SUCCESS':
            console.log('bbbb');
          break;
      }
    });
```
How can I log in other than this code?

**Comment by devcycode** [comment]
Is it possible to access data.code without using this function?
```
youtube.ev.on('auth', (data) => {
      switch (data.status) {
        case 'AUTHORIZATION_PENDING':
          console.log(`
                Hello! On your phone or computer,
                go to ${data.verification_url} and enter
                the code ${data.code}.
              `);
              next();
          break;

          case 'SUCCESS':
            console.log('bbbb');
          break;
      }
    });
```
