### ISSUE TITLE
1.4.4 Streaming data fetching results in a parsing error

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#134]
### Steps to reproduce

I just tried fetching the streaming data. I don't know anything about InnerTube API, so I'm not sure if this error is normal. It still retrieves the data, but this error concerns me.

### Failure Logs

```shell
Server error:  ParsingError: Could not transform n-token, download may be throttled.
    at NToken.transform (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/deciphers/NToken.js:55:21)
    at /home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/Innertube.js:432:125
    at Array.forEach (<anonymous>)
    at Innertube.#chooseFormat (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/Innertube.js:420:13)
    at Innertube.getStreamingData (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/Innertube.js:488:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (file:///home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/index.js:203:33) {
  info: {
    original_token: 'YwXptdr-M4sGuFl',
    stack: 'SyntaxError: Unexpected token u in JSON at position 189\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at NToken.#getTransformationData (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/deciphers/NToken.js:74:17)\n' +
      '    at NToken.transform (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/deciphers/NToken.js:20:56)\n' +
      '    at /home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/Innertube.js:432:125\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at Innertube.#chooseFormat (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/Innertube.js:420:13)\n' +
      '    at Innertube.getStreamingData (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/Innertube.js:488:46)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async WebSocket.<anonymous> (file:///home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/index.js:203:33)'
  },
  date: 2022-08-11T20:11:06.390Z,
  version: '1.4.4'
}
```

### Expected behavior

I expected this to fetch the data without any errors.

### Current behavior

It fetches the data correctly but gives this parsing error.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Yup, YouTube updated their n token algorithm. I'm gonna update the NPM version later today.
Thanks.
