### ISSUE TITLE
TypeError at parser/youtube/Search.js:30:45 with Promise.<Search>::getContinuation

### ISSUE THREAD

**Issue by Taaaaaooooo** [LuanRT/YouTube.js#172]
### Steps to reproduce

**Dockerfile**

```dockerfile
FROM node:lts-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 3000
RUN chown -R node /usr/src/app
USER node
CMD ["node", "index.js"]
```

**index.js**

```js
const { Innertube } = require('youtubei.js');

(async () => {
    const youtube = await Innertube.create();
    let res = await youtube.search("say");
    console.log("OK");
    let resContinuation = await res.getContinuation();
      
})();
```

**package.json**

```json
{
  "name": "ytfilter",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "youtubei.js": "^2.0.1"
  }
}
```

### Failure Logs

```shell
OK
/usr/src/node_modules/youtubei.js/dist/src/parser/youtube/Search.js:30
        const contents = this.page.contents.item().as(TwoColumnSearchResults_1.default).primary_contents.item().key('contents').parsed().array() ||
                                            ^

TypeError: Cannot read properties of null (reading 'item')
    at new Search (/usr/src/node_modules/youtubei.js/dist/src/parser/youtube/Search.js:30:45)
    at Search.<anonymous> (/usr/src/node_modules/youtubei.js/dist/src/parser/youtube/Search.js:79:20)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/node_modules/youtubei.js/dist/src/parser/youtube/Search.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected behavior

Returning a fulfilled `Promise.<Search>`

### Current behavior

Don't check for null value. Trowing TypeError.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Seems like YouTube made a small change (there's a new renderer called `TitleAndButtonListHeader` and we're not checking whether the contents prop is valid). I'll update the library today. Anyway, thanks for reporting:thumbsup:

**Comment by LuanRT** [comment]
Fixed. Update to v2.0.2 and let me know if it works. 
Again, thanks.

**Comment by Taaaaaooooo** [comment]
> Fixed. Update to v2.0.2 and let me know if it works. Again, thanks.

All good, you're welcome, thanks for your work. :)
