### ISSUE TITLE
<2.0.2>CollaboratorInfoCardContent not found!

### ISSUE THREAD

**Issue by USERSATOSHI** [LuanRT/YouTube.js#174]
### Steps to reproduce

```js
const InnerTube =  require("youtubei.js").default;
(async() => {
  const yt = await InnerTube.create();
  await  yt.getBasicInfo("60ItHLz5WEA","WEB");
})();
```

### Failure Logs

```shell
InnertubeError: CollaboratorInfoCardContent not found!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at Function.formatError (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:357:33)
    at Function.parseItem (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:279:22)
    at Function.parse (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:321:53)
    at new Card (D:\music\node_modules\youtubei.js\dist\src\parser\classes\Card.js:12:40)
    at Function.parseItem (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:274:32)
    at Function.parseArray (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:289:37)
    at new CardCollection (D:\music\node_modules\youtubei.js\dist\src\parser\classes\CardCollection.js:12:38)
    at Function.parseItem (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:274:32)
    at Function.parseResponse (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:217:27)
    at new VideoInfo (D:\music\node_modules\youtubei.js\dist\src\parser\youtube\VideoInfo.js:70:38) {
  info: {
    channelAvatar: { thumbnails: [Array] },
    customText: { simpleText: 'Walker Gaming' },
    channelName: { simpleText: 'Walker Gaming' },
    subscriberCountText: { simpleText: '85.7K subscribers' },
    endpoint: {
      clickTrackingParams: 'CDoQ1TYiEwj9jvLXr4f6AhV6mmMGHVJnCScyBWNhcmRz',
      commandMetadata: [Object],
      browseEndpoint: [Object]
    },
    trackingParams: 'CDoQ1TYiEwj9jvLXr4f6AhV6mmMGHVJnCSc='
  },
  date: 2022-09-09T09:15:00.617Z,
  version: '2.0.2'
}
InnertubeError: CollaboratorInfoCardContent not found!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at Function.formatError (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:357:33)
    at Function.parseItem (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:279:22)
    at Function.parse (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:321:53)
    at new Card (D:\music\node_modules\youtubei.js\dist\src\parser\classes\Card.js:12:40)
    at Function.parseItem (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:274:32)
    at Function.parseArray (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:289:37)
    at new CardCollection (D:\music\node_modules\youtubei.js\dist\src\parser\classes\CardCollection.js:12:38)
    at Function.parseItem (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:274:32)
    at Function.parseResponse (D:\music\node_modules\youtubei.js\dist\src\parser\index.js:217:27)
    at new VideoInfo (D:\music\node_modules\youtubei.js\dist\src\parser\youtube\VideoInfo.js:70:38) {
  info: {
    channelAvatar: { thumbnails: [Array] },
    customText: { simpleText: 'Walker Gaming' },
    channelName: { simpleText: 'Walker Gaming' },
    subscriberCountText: { simpleText: '85.7K subscribers' },
    endpoint: {
      clickTrackingParams: 'CFEQ1TYiEwiX0q7Yr4f6AhVgxDgGHW1vAS8yBWNhcmRz',
      commandMetadata: [Object],
      browseEndpoint: [Object]
    },
    trackingParams: 'CFEQ1TYiEwiX0q7Yr4f6AhVgxDgGHW1vAS8='
  },
  date: 2022-09-09T09:15:01.224Z,
  version: '2.0.2'
}
```

### Expected behavior

expected to work normally without sending any error messages

### Current behavior

it does send the info but 
also sends that error in console

### Version

Default

### Anything else?

seems like this only happens on some tracks.
I tried on some other tracks and it didn't spam the console.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Thanks for reporting, these kind of warnings usually don't interfere with the actual result. The library always prints a warning when something new/unexpected pops up in an InnerTube response.
