### ISSUE TITLE
2.0.2 Failed to log-in with OAuth.

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#175]
### Steps to reproduce

```
const { Innertube, UniversalCache } = require('youtubei.js');

(async () => {
  const yt = await Innertube.create({
    // required if you wish to use OAuth#cacheCredentials
    cache: new UniversalCache()
  });

  // 'auth-pending' is fired with the info needed to sign in via OAuth.
  yt.session.on('auth-pending', (data) => {
    console.log(`Go to ${data.verification_url} in your browser and enter code ${data.user_code} to authenticate.`);
  });

  // 'auth' is fired once the authentication is complete
  yt.session.on('auth', ({ credentials }) => {
    console.log('Sign in successful:', credentials);
  });

  // 'update-credentials' is fired when the access token expires, if you do not save the updated credentials any subsequent request will fail
  yt.session.on('update-credentials', ({ credentials }) => {
    console.log('Credentials updated:', credentials);
  });

  // Attempt to sign in
  await yt.session.signIn();

  // ... do something after sign in
  console.log(yt.getLibrary())

  // You may cache the session for later use
  // If you use this, the next call to signIn won't fire 'auth-pending' instead just 'auth'.
  await yt.session.oauth.cacheCredentials();
})();
```

### Failure Logs

```shell
/home/stas/Sync/Documents/yt-demo/node_modules/youtubei.js/dist/src/core/OAuth.js:185
            return __classPrivateFieldGet(this, _OAuth_session, "f").emit('auth-error', new Utils_1.OAuthError('Could not obtain user code.', { status: 'FAILED', error: err }));
                                                                                        ^

OAuthError: Could not obtain user code.
    at OAuth.<anonymous> (/home/stas/Sync/Documents/yt-demo/node_modules/youtubei.js/dist/src/core/OAuth.js:185:89)
    at Generator.throw (<anonymous>)
    at rejected (/home/stas/Sync/Documents/yt-demo/node_modules/youtubei.js/dist/src/core/OAuth.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  info: {
    status: 'FAILED',
    error: TypeError: fetch failed
        at Object.processResponse (/home/stas/Sync/Documents/yt-demo/node_modules/undici/lib/fetch/index.js:199:23)
        at /home/stas/Sync/Documents/yt-demo/node_modules/undici/lib/fetch/index.js:928:38
        at node:internal/process/task_queues:140:7
        at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
        at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      cause: ConnectTimeoutError: Connect Timeout Error
          at onConnectTimeout (/home/stas/Sync/Documents/yt-demo/node_modules/undici/lib/core/connect.js:131:24)
          at /home/stas/Sync/Documents/yt-demo/node_modules/undici/lib/core/connect.js:78:46
          at Immediate._onImmediate (/home/stas/Sync/Documents/yt-demo/node_modules/undici/lib/core/connect.js:119:9)
          at process.processImmediate (node:internal/timers:471:21) {
        code: 'UND_ERR_CONNECT_TIMEOUT'
      }
    }
  },
  date: 2022-09-09T10:38:53.626Z,
  version: '2.0.2'
}

Node.js v18.8.0
```

### Expected behavior
User's library to be printed.

### Current behavior
A crash.

### Version
Default

**Comment by walking-octopus** [comment]
For some reason, it worked on the second try. Should I close this issue?

**Comment by LuanRT** [comment]
There was probably a small disturbance on your network, given Undici reports a timeout.

**Comment by walking-octopus** [comment]
Ok. Thanks!
