### ISSUE TITLE
v2.2.3 Posting Comments Doesn't work

### ISSUE THREAD

**Issue by ElectroYModz** [LuanRT/YouTube.js#204]
### Steps to reproduce

login
post comment

### Failure Logs

```shell
InnertubeError: Request to https://www.youtube.com/youtubei/v1/comment/create_comment?prettyPrint=false&alt=json failed with status 403
    at HTTPClient.<anonymous> (D:\Users\PC\Documents\YT\Commenter\node_modules\youtubei.js\dist\src\utils\HTTPClient.js:112:19)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Users\PC\Documents\YT\Commenter\node_modules\youtubei.js\dist\src\utils\HTTPClient.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  info: '{\n' +
    '  "error": {\n' +
    '    "code": 403,\n' +
    '    "message": "The caller does not have permission",\n' +
    '    "errors": [\n' +
    '      {\n' +
    '        "message": "The caller does not have permission",\n' +
    '        "domain": "global",\n' +
    '        "reason": "forbidden"\n' +
    '      }\n' +
    '    ],\n' +
    '    "status": "PERMISSION_DENIED"\n' +
    '  }\n' +
    '}\n',
  date: 2022-09-24T01:09:20.544Z,
  version: '2.2.3'
}
```

### Expected behavior

post a comment

### Current behavior

doesn't

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by itsmenewbie03** [comment]
Just tested this recently and I did not encounter any issues.

**Comment by LuanRT** [comment]
Can't reproduce, are you perhaps using a brand account? They are known to be problematic.

**Comment by ElectroYModz** [comment]
> Can't reproduce, are you perhaps using a brand account? They are known to be problematic.

could be that
