### ISSUE TITLE
2.2.3 No matching formats found

### ISSUE THREAD

**Issue by imagineeeinc** [LuanRT/YouTube.js#213]
### Steps to reproduce

run the download function on a server eg.: railway.app

### Failure Logs

```shell
InnertubeError: No matching formats found
at VideoInfo.chooseFormat (/app/node_modules/youtubei.js/dist/src/parser/youtube/VideoInfo.js:311:19)
at VideoInfo.<anonymous> (/app/node_modules/youtubei.js/dist/src/parser/youtube/VideoInfo.js:367:33)
at Generator.next (<anonymous>)
at /app/node_modules/youtubei.js/dist/src/parser/youtube/VideoInfo.js:8:71
at new Promise (<anonymous>)
at __awaiter (/app/node_modules/youtubei.js/dist/src/parser/youtube/VideoInfo.js:4:12)
at VideoInfo.download (/app/node_modules/youtubei.js/dist/src/parser/youtube/VideoInfo.js:359:16)
at Innertube.<anonymous> (/app/node_modules/youtubei.js/dist/src/Innertube.js:226:25)
at Generator.next (<anonymous>)
at fulfilled (/app/node_modules/youtubei.js/dist/src/Innertube.js:5:58) {
info: {
options: { quality: '144p', type: 'audio', format: 'mp4', range: undefined }
},
date: 2022-09-29T19:26:43.579Z,
version: '2.2.3'
}
```

### Expected behavior

On desktop it runs fine and should stream the audio

### Current behavior

returns this random error: No matching formats found

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Hey there, it is because you're setting `quality` to `144p` while `type` is `audio` 😆.

To solve this, you can change the quality config to `best` or ` bestefficiency`.

Thanks and have a great day!

**Comment by imagineeeinc** [comment]
Oh, if it is then why does it work on my desktop (windows 11), but not on a server (i think it runs Debian). The reason why I ask is because I am streaming the audio and `best` or `bestefficiency` are not fast enough to respond compared to 144p, if I have no other choice I guess I'll use that.

**Comment by LuanRT** [comment]
Using `144p` won't really give you any audio format, so it is useless to use it if you're targeting audio only streams. If you need low bitrate audio then `bestefficiency` is what you should use.

**Comment by imagineeeinc** [comment]
ok I'll try it out
