### ISSUE TITLE
V2.0.0 --- InnertubeError: Something went wrong at MusicDetailHeader!

### ISSUE THREAD

**Issue by titong0** [LuanRT/YouTube.js#215]
### Steps to reproduce

I'm no sure why but calling `client.music.getAlbum();` with the id `"MPREb_Ml86XqtmqaJ"` crashes.

### Failure Logs

```shell
InnertubeError: Something went wrong at MusicDetailHeader!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
at Function.formatError (/app/node_modules/youtubei.js/dist/src/parser/index.js:317:22)
at Function.parseItem (/app/node_modules/youtubei.js/dist/src/parser/index.js:268:22)
at Function.parse (/app/node_modules/youtubei.js/dist/src/parser/index.js:310:53)
at Function.parseResponse (/app/node_modules/youtubei.js/dist/src/parser/index.js:178:28)
at new Album (/app/node_modules/youtubei.js/dist/src/parser/ytmusic/Album.js:27:67)
at Music.<anonymous> (/app/node_modules/youtubei.js/dist/src/core/Music.js:121:20)
at Generator.next (<anonymous>)
at fulfilled (/app/node_modules/youtubei.js/dist/src/core/Music.js:5:58)
at processTicksAndRejections (node:internal/process/task_queues:96:5) {
info: {
stack: "TypeError: Cannot read properties of undefined (reading 'text')\n" +
'    at new MusicDetailHeader (/app/node_modules/youtubei.js/dist/src/parser/classes/MusicDetailHeader.js:17:88)\n' +
'    at Function.parseItem (/app/node_modules/youtubei.js/dist/src/parser/index.js:263:32)\n' +
'    at Function.parse (/app/node_modules/youtubei.js/dist/src/parser/index.js:310:53)\n' +
'    at Function.parseResponse (/app/node_modules/youtubei.js/dist/src/parser/index.js:178:28)\n' +
'    at new Album (/app/node_modules/youtubei.js/dist/src/parser/ytmusic/Album.js:27:67)\n' +
'    at Music.<anonymous> (/app/node_modules/youtubei.js/dist/src/core/Music.js:121:20)\n' +
'    at Generator.next (<anonymous>)\n' +
'    at fulfilled (/app/node_modules/youtubei.js/dist/src/core/Music.js:5:58)\n' +
'    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
},
date: 2022-10-06T17:47:24.863Z,
version: '2.0.0'
}
```

### Expected behavior

not crash

### Current behavior

crashes

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by heesungjang** [comment]
Hi @LuanRT, Can i work on this issue if not assigned to anybody? thanks!!

**Comment by LuanRT** [comment]
> Hi @LuanRT, Can i work on this issue if not assigned to anybody? thanks!!

Sure!
