### ISSUE TITLE
2.3.2 There are no continuations

### ISSUE THREAD

**Issue by slidenerd** [LuanRT/YouTube.js#239]
### Steps to reproduce

Use innertube youtube instance to search for 'ghost recon future soldier' with filter set to last 24 hrs

I am using the function below to comment on relevant videos but it never fetches the next page. Wasnt a problem 2 days ago

```

async function fetchAllSearchResults({
  youtube,
  searchTerm,
  randomElement,
  responses,
  debug,
}) {
  let index = 1;
  let estimatedSize = 1;

  // Refer to ./responses/comment-failed.json and ./responses/comment-success.json to see what happens when posting a comment fails/succeeds
  async function processResult(youtube, result) {
    // Keep higher numbers to prevent getting caught
    const DELAY =
      MIN_DELAY + Math.floor(Math.random() * (MAX_DELAY - MIN_DELAY));

    // YouTube search returns a lot of false positives so we apply our own filter to confirm that only titles containing 'ghost recon future soldier' in some form will be considered

    if (!isGhostReconFutureSoldierVideo(result.title.text)) {
      console.log(
        `skip index:${index}/${estimatedSize} video:${result.id} channel:${result.author.name} REASON:title does not match "${searchTerm}" title:${result.title.text}`
      );
      index++;
      return;
    }

    const shouldPost = getShouldPostComment(result);
    if (shouldPost.isExisting) {
      console.log(
        `skip index:${index}/${estimatedSize} video:${result.id} channel:${result.author.name} REASON:exists`
      );
      index++;
      return;
    }
    if (shouldPost.isBlacklisted) {
      console.log(
        `skip index:${index}/${estimatedSize} video:${result.id} channel:${result.author.name} REASON:blacklisted`
      );
      index++;
      return;
    }
    if (shouldPost.hasCommentedTooManyTimes) {
      console.log(
        `skip index:${index}/${estimatedSize} video:${result.id} channel:${result.author.name} REASON:commented more than ${MAX_NUMBER_OF_COMMENTS_PER_CHANNEL} times`
      );
      index++;
      return;
    }

    const comment = randomElement(responses);
    const response = await youtube.interact.comment(result.id, comment);
    const { success } = response;
    if (success) {
      try {
        console.log(
          `EXEC index:${index}/${estimatedSize} video:${result.id} channel:${result.author.name} link:https://youtube.com/watch?v=${result.id} comment:${comment}`
        );
        createCommentHistory({
          videoId: result.id,
          videoTitle: result.title.text,
          authorId: result.author.id,
          authorName: result.author.name,
          authorUrl: result.author.url,
          viewCount: result.view_count.text,
          duration: result.duration.seconds,
          searchTerm: searchTerm,
          comment,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        });
        index++;
      } catch (error) {
        console.error(error, result.id);
      }
    }
    await setTimeout(DELAY);
  }

  async function processResults(youtube, results) {
    for (let i = 0; i < results.length; i++) {
      await processResult(youtube, results[i]);
    }
  }

  async function fetchNextPage(previousResults) {
    if (previousResults.results && previousResults.results.length) {
      if (typeof previousResults.getContinuation === 'undefined' || typeof previousResults.getContinuation === null) {
        console.warn('Did not find a getContinuation() method on previousResults', Object.keys(previousResults));
        return
      }
      const results = await previousResults.getContinuation();
      await processResults(youtube, results.results);
      debug && saveResultsToFile(results, searchTerm);
      await fetchNextPage(results);
    }
  }
  const results = await youtube.search(searchTerm, {
    upload_date: "today",
    type: "video",
  });

  estimatedSize = results.estimated_results;
  console.log('how many results', estimatedSize);
  await processResults(youtube, results.results);
  debug && saveResultsToFile(results, searchTerm);
  await fetchNextPage(results);
}

```

### Failure Logs

```shell
t
/Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:202
                    throw new Utils_1.InnertubeError('There are no continuations');
                          ^

InnertubeError: There are no continuations
    at Search.<anonymous> (/Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:202:27)
    at Generator.next (<anonymous>)
    at /Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:27:12)
    at Search.getContinuationData (/Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:197:16)
    at Search.<anonymous> (/Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:208:29)
    at Generator.next (<anonymous>)
    at /Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:31:71
    at new Promise (<anonymous>) {
  date: 2022-11-16T02:56:19.404Z,
  version: '2.3.2'
}
```

### Expected behavior

I should be able to load the next page

### Current behavior

Throws an error

### Version

Default

### Checklist

- [ ] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by slidenerd** [comment]
Not an issue on the latest version, sorry my bad

**Comment by slidenerd** [comment]
Sorry my bad, just tested on 2.4.1, bug is still there

**Comment by slidenerd** [comment]
The final result on page 1 has no title on it either, weird
```

This result has no title {"type":"Message","text":"No more results"}
/Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:193
                    throw new Utils_1.InnertubeError('There are no continuations');
                          ^

InnertubeError: There are no continuations
    at Search.<anonymous> (/Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:193:27)
    at Generator.next (<anonymous>)
    at /Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:27:12)
    at Search.getContinuationData (/Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:188:16)
    at Search.<anonymous> (/Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:199:29)
    at Generator.next (<anonymous>)
    at /Users/vr/Desktop/code/FINISHED/yt-comment-bot/node_modules/youtubei.js/dist/src/core/Feed.js:31:71
    at new Promise (<anonymous>) {
  date: 2022-11-16T03:07:17.446Z,
  version: '2.4.1'
}
```

**Comment by slidenerd** [comment]
This is what each page looks like in JSON after I saved the results

[Page 1](https://pastebin.com/B1VfnXhs)
[Page 2](https://pastebin.com/b0fR4KEa)
[Last Page](https://pastebin.com/g59MgE15)

**Comment by LuanRT** [comment]
Just did a simple test and it seems to be normal behaviour. Code snippet I used:
```ts
let search = await yt.search('ghost recon future soldier', { type: 'video', upload_date: 'today' });

while (search.has_continuation) {
  search = await search.getContinuation();
  console.log(search);
}
```

Which results in:
```
Search {
  results: [ Message { type: 'Message', text: 'No more results' } ],
  refinements: [],
  estimated_results: 22,
  watch_card: { header: null, call_to_action: null, sections: [] },
  refinement_cards: { header: null, cards: [] }
}
```

This 'No more results'  message is also displayed on the website. So I would say not many videos are being uploaded about that topic.
