### ISSUE TITLE
[2.5.0] : InnertubeError: Something went wrong at PlayerMicroformat!

### ISSUE THREAD

**Issue by USERSATOSHI** [LuanRT/YouTube.js#244]
### Steps to reproduce

\<InnerTube\>.getBasicInfo("dHQ0eU39HKk","WEB");

### Failure Logs

```shell
InnertubeError: Something went wrong at PlayerMicroformat!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at Parser._Parser_printError (D:\projects-next\node_modules\youtubei.js\dist\src\parser\index.js:403:18)
    at Parser.parseItem (D:\projects-next\node_modules\youtubei.js\dist\src\parser\index.js:305:77)       
    at Parser.parseResponse (D:\projects-next\node_modules\youtubei.js\dist\src\parser\index.js:212:52)   
    at new VideoInfo (D:\projects-next\node_modules\youtubei.js\dist\src\parser\youtube\VideoInfo.js:71:38)
    at Innertube.<anonymous> (D:\projects-next\node_modules\youtubei.js\dist\src\Innertube.js:73:20)      
    at Generator.next (<anonymous>)
    at fulfilled (D:\projects-next\node_modules\youtubei.js\dist\src\Innertube.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  info: {
    stack: "TypeError: Cannot read properties of undefined (reading 'iframeUrl')\n" +
      '    at new PlayerMicroformat (D:\\projects-next\\node_modules\\youtubei.js\\dist\\src\\parser\\classes\\PlayerMicroformat.js:16:36)\n' +
      '    at Parser.parseItem (D:\\projects-next\\node_modules\\youtubei.js\\dist\\src\\parser\\index.js:300:32)\n' +
      '    at Parser.parseResponse (D:\\projects-next\\node_modules\\youtubei.js\\dist\\src\\parser\\index.js:212:52)\n' +
      '    at new VideoInfo (D:\\projects-next\\node_modules\\youtubei.js\\dist\\src\\parser\\youtube\\VideoInfo.js:71:38)\n' +
      '    at Innertube.<anonymous> (D:\\projects-next\\node_modules\\youtubei.js\\dist\\src\\Innertube.js:73:20)\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at fulfilled (D:\\projects-nexts\\node_modules\\youtubei.js\\dist\\src\\Innertube.js:5:58)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
  },
  date: 2022-11-25T19:19:53.552Z,
  version: '2.5.0'
}
```

### Expected behavior

to send info

### Current behavior

error

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
https://github.com/LuanRT/YouTube.js/blob/6caa679df6ddc77d25be02dcb7355b722ab268aa/src/parser/classes/PlayerMicroformat.ts#L44-L50
Seems like it's trying to access the embed object when it's not present in the `PlayerMicroformat` renderer, should be an easy fix.

> to send info

The parser is able to keep up even after an error happens, so I'm pretty sure it still returns a response (though it will be missing data from `PlayerMicroformat`, as nodes that error out are simply ignored).

Thanks for reporting!

**Comment by USERSATOSHI** [comment]
hmm i will check for response again tho i am also experiencing circular directory issue 
so that might be the reason i didn't receive any info 🥲
