### ISSUE TITLE
3.1.0 : InnertubeError: RichMetadataRow not found!

### ISSUE THREAD

**Issue by RikiNozomu** [LuanRT/YouTube.js#327]
### Steps to reproduce

import { Innertube } from 'youtubei.js';
const yt = await Innertube()
await yt.getInfo("dU6-129Ch10"/*video["id"]*/).catch(() => {})

### Failure Logs

```shell
InnertubeError: RichMetadataRow not found!
This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!
    at Function._Parser_printError (/Users/rikinozomu/Desktop/vth-project/vth-backend/node_modules/youtubei.js/src/parser/parser.ts:453:9)
    at Function.parseItem (/Users/rikinozomu/Desktop/vth-project/vth-backend/node_modules/youtubei.js/src/parser/parser.ts:300:27)
    at Function.parseArray (/Users/rikinozomu/Desktop/vth-project/vth-backend/node_modules/youtubei.js/src/parser/parser.ts:318:29)
    at new MetadataRowContainer (/Users/rikinozomu/Desktop/vth-project/vth-backend/node_modules/youtubei.js/src/parser/classes/MetadataRowContainer.ts:11:24)
    at Function.parseItem (/Users/rikinozomu/Desktop/vth-project/vth-backend/node_modules/youtubei.js/src/parser/parser.ts:295:24)
    at new VideoSecondaryInfo (/Users/rikinozomu/Desktop/vth-project/vth-backend/node_modules/youtubei.js/src/parser/classes/VideoSecondaryInfo.ts:31:28)
    at Function.parseItem (/Users/rikinozomu/Desktop/vth-project/vth-backend/node_modules/youtubei.js/src/parser/parser.ts:295:24)
    at Function.parseArray (/Users/rikinozomu/Desktop/vth-project/vth-backend/node_modules/youtubei.js/src/parser/parser.ts:318:29)
    at new TwoColumnWatchNextResults (/Users/rikinozomu/Desktop/vth-project/vth-backend/node_modules/youtubei.js/src/parser/classes/TwoColumnWatchNextResults.ts:13:27)
    at Function.parseItem (/Users/rikinozomu/Desktop/vth-project/vth-backend/node_modules/youtubei.js/src/parser/parser.ts:295:24) {
  info: {
    contents: [ [Object], [Object] ],
    trackingParams: 'CJcEEN2tBBhOIhMI44D_nZ62_QIV5kGdCR19qgnJ'
  },
  date: 2023-02-27T17:34:22.954Z,
  version: '3.1.0'
}
```

### Expected behavior

No error show this.

### Current behavior

show this error log.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by Rydann** [comment]
I just saw this and I think I might have unintentionally fixed this with #333 🤣
