### ISSUE TITLE
GridShow not found when `getChannel("UCqVDpXKLmKeBU_yyt_QkItQ")`

### ISSUE THREAD

**Issue by Yonle** [LuanRT/YouTube.js#359]
```
InnertubeError: GridShow not found!
This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!
    at Parser._Parser_printError (/data/data/com.termux/files/home/ytmous/node_modules/youtubei.js/bundle/node.cjs:9890:25)
    at Parser.parseItem (/data/data/com.termux/files/home/ytmous/node_modules/youtubei.js/bundle/node.cjs:9757:72)
    at Parser.parseArray (/data/data/com.termux/files/home/ytmous/node_modules/youtubei.js/bundle/node.cjs:9767:29)
    at new HorizontalList (/data/data/com.termux/files/home/ytmous/node_modules/youtubei.js/bundle/node.cjs:5312:33)
    at Parser.parseItem (/data/data/com.termux/files/home/ytmous/node_modules/youtubei.js/bundle/node.cjs:9753:24)
    at new Shelf (/data/data/com.termux/files/home/ytmous/node_modules/youtubei.js/bundle/node.cjs:8211:35)
    at Parser.parseItem (/data/data/com.termux/files/home/ytmous/node_modules/youtubei.js/bundle/node.cjs:9753:24)
    at Parser.parse (/data/data/com.termux/files/home/ytmous/node_modules/youtubei.js/bundle/node.cjs:9784:29)
    at new ItemSection (/data/data/com.termux/files/home/ytmous/node_modules/youtubei.js/bundle/node.cjs:5401:36)
    at Parser.parseItem (/data/data/com.termux/files/home/ytmous/node_modules/youtubei.js/bundle/node.cjs:9753:24) {
  info: {
    title: { simpleText: '30 Days With: Anuel' },
    thumbnailRenderer: { showCustomThumbnailRenderer: [Object] },
    navigationEndpoint: {
      clickTrackingParams: 'CJ4CEJeLARgCIhMIzb2U9ezc_QIVbM-gAh3ACQ0V',
      commandMetadata: [Object],
      browseEndpoint: [Object]
    },
    shortBylineText: { runs: [Array] },
    longBylineText: { runs: [Array] },
    trackingParams: 'CJ4CEJeLARgCIhMIzb2U9ezc_QIVbM-gAh3ACQ0V',
    thumbnailOverlays: [ [Object] ]
  },
  date: 2023-03-15T02:07:33.290Z,
  version: '3.3.0'
}
```

**Comment by LuanRT** [comment]
Fixed by 8ef4b42.
