### ISSUE TITLE
3.3.0 LiveChatReportModerationStateCommand not found

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [LuanRT/YouTube.js#361]
### Steps to reproduce

All these steps were performed on [FreeTube](https://github.com/FreeTubeApp/FreeTube/)

1. Go to https://www.youtube.com/playlist?list=PLU12uITxBEPH5i1LeWBM32A5T9iWRxvYl
2. Cycle through live streams until this error pops up

### Failure Logs

```shell
LiveChatReportModerationStateCommand not found!
This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!
    at cE.<anonymous> (renderer.js:2:1254938)
    at cE.parseItem (renderer.js:2:1249780)
    at cE.parse (renderer.js:2:1250147)
    at new _E (renderer.js:2:1258515)
    at cE.parseLC (renderer.js:2:1250588)
    at cE.parseResponse (renderer.js:2:1245431)
    at Object.<anonymous> (renderer.js:2:1366962)
    at Generator.next (<anonymous>)
    at a (renderer.js:2:1352844)
```

### Expected behavior

I have no idea what it should do because everything seems to load fine.

### Current behavior

See Expected behavior.

### Version

Default

### Checklist

- [ ] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by sooxt98** [comment]
getting this too
``` bash
InnertubeError: LiveChatReportModerationStateCommand not found!This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!    at Function._Parser_printError (D:\tzzq\fishio\node_modules\youtubei.js\src\parser\parser.ts:461:9)    at Function.parseItem (D:\tzzq\fishio\node_modules\youtubei.js\src\parser\parser.ts:308:27)    at Function.parse (D:\tzzq\fishio\node_modules\youtubei.js\src\parser\parser.ts:354:29)    at new LiveChatContinuation (D:\tzzq\fishio\node_modules\youtubei.js\src\parser\parser.ts:665:27)    at Function.parseLC (D:\tzzq\fishio\node_modules\youtubei.js\src\parser\parser.ts:382:14)    at Function.parseResponse (D:\tzzq\fishio\node_modules\youtubei.js\src\parser\parser.ts:106:68)    at Actions.<anonymous> (D:\tzzq\fishio\node_modules\youtubei.js\src\core\Actions.ts:196:36)    at Generator.next (<anonymous>)    at fulfilled (D:\tzzq\fishio\node_modules\youtubei.js\bundle\node.cjs:14340:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  info: {},
  date: 2023-03-21T18:58:38.381Z,
  version: '3.3.0'
}
```

**Comment by LuanRT** [comment]
Could this be the “Slow-mode is on” message? I'll probably have to look around a bit in order to fix it.

If anyone is able to confirm this please let me know.
