### ISSUE TITLE
4.0.1 "Expected an api_url, but none was found" error on `Comment#like()`

### ISSUE THREAD

**Issue by virtueer** [LuanRT/YouTube.js#364]
### Steps to reproduce

```
 while (true) {
      for (const { comment } of comments.contents || []) {
        console.log(comment.content.toString(), comment.comment_id)
        if (!(comment.comment_id === comment_id))
          continue

        response = await comment.like() // throws
        break;
      }

      if (comments.has_continuation)
        comments = await comments.getContinuation()
      else
        break
    }
```

videoId=8YEnZpwUCOI
commentId=UgypUilAd4sst_VgPk54AaABAg

### Failure Logs

```shell
------- error handled -> exception
Error: Expected an api_url, but none was found, this is a bug.
    at NavigationEndpoint.call (C:\Users\erdem\Desktop\youtube-request-library\node_modules\youtubei.js\src\parser\classes\NavigationEndpoint.ts:94:13)
    at Comment.<anonymous> (C:\Users\erdem\Desktop\youtube-request-library\node_modules\youtubei.js\src\parser\classes\comments\Comment.ts:97:12)
    at Generator.next (<anonymous>)
    at C:\Users\erdem\Desktop\youtube-request-library\node_modules\youtubei.js\bundle\node.cjs:4351:67
    at new Promise (<anonymous>)
    at __classPrivateFieldGet (C:\Users\erdem\Desktop\youtube-request-library\node_modules\youtubei.js\bundle\node.cjs:4329:10)
    at Comment.like (C:\Users\erdem\Desktop\youtube-request-library\node_modules\youtubei.js\src\parser\classes\comments\Comment.ts:84:10)
    at YoutubeService.like_comment (C:\Users\erdem\Desktop\youtube-request-library\src\modules\youtube\youtube.service.ts:77:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at C:\Users\erdem\Desktop\youtube-request-library\node_modules\@nestjs\core\router\router-execution-context.js:46:28
-------
```

### Expected behavior

I was expecting api response

### Current behavior

------- error handled -> exception
Error: Expected an api_url, but none was found, this is a bug.
    at NavigationEndpoint.call (\node_modules\youtubei.js\src\parser\classes\NavigationEndpoint.ts:94:13)
    at Comment.<anonymous> (\node_modules\youtubei.js\src\parser\classes\comments\Comment.ts:97:12)
    at Generator.next (<anonymous>)
    at \node_modules\youtubei.js\bundle\node.cjs:4351:67
    at new Promise (<anonymous>)
    at __classPrivateFieldGet (\node_modules\youtubei.js\bundle\node.cjs:4329:10)
    at Comment.like (\node_modules\youtubei.js\src\parser\classes\comments\Comment.ts:84:10)
    at YoutubeService.like_comment (\src\modules\youtube\youtube.service.ts:77:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at \node_modules\@nestjs\core\router\router-execution-context.js:46:28
------- 

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by virtueer** [comment]
Also comment_id always same

**Comment by LuanRT** [comment]
> Also comment_id always same but content changes

That's interesting. Are you sure it's not something else on your codebase making the comment id appear the same? Otherwise, it must be YouTube itself doing something funky, as the library does not do any processing regarding the id. 

I'll look into this problem today, thanks for reporting!
