### ISSUE TITLE
4.0.1 Errpr thrown in built Electron app

### ISSUE THREAD

**Issue by Araxeus** [LuanRT/YouTube.js#365]
### Steps to reproduce

Build an Electron app using `require('youtubei.js');`

It will work in dev mode, but once the app is built then it will fail to load

### Failure Logs

```shell
TypeError: Cannot read properties of undefined (reading 'url')
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\node_modules\youtubei.js\bundle\node.cjs:16362:33)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\plugins\downloader\back.js:23:46)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
TypeError: Cannot read properties of undefined (reading 'url')
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\node_modules\youtubei.js\src\platform\node.ts:104:33)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\plugins\downloader\back.js:23:46)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
TypeError: Cannot read properties of undefined (reading 'url')
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\node_modules\youtubei.js\src\platform\node.ts:104:33)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\plugins\crossfade\back.js:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
TypeError: Cannot read properties of undefined (reading 'url')
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\node_modules\youtubei.js\src\platform\node.ts:104:33)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\plugins\downloader\back.js:23:46)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
Error occurred in handler for 'audio-url': No handler registered for 'audio-url'
TypeError: Cannot read properties of undefined (reading 'url')
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\node_modules\youtube    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\plugins\downloader\back.js:23:46)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
(node:6124) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'url')
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\node_modules\youtubei.js\src\platform\node.ts:104:33)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Araxeus\AppData\Local\Programs\youtube-music\resources\app.asar\plugins\downloader\back.js:23:46)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
(Use `Youtube Music --trace-warnings ...` to show where the warning was created)
(node:6124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 31)
```

### Expected behavior

The app loads

### Current behavior

The app fails to load

### Version

Default

### Anything else?

I actually researched the problem a bit and isolated its origin to this line:

https://github.com/LuanRT/YouTube.js/blob/1c72a41675e47f711bd61ebb898bca5527406a79/src/platform/node.ts#L28

this seems to not resolve in a built asar (which electron does)

and then the following lines throw:

https://github.com/LuanRT/YouTube.js/blob/1c72a41675e47f711bd61ebb898bca5527406a79/src/platform/node.ts#L102-L107

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by Araxeus** [comment]
@LuanRT We integrated this library in https://github.com/th-ch/youtube-music

Tests ran fine in dev mode, and it built fine, so the changes were merged

Now upon building the app, I suddenly encounter this error :S

This is kinda high priority, would love a quick solution thanks ♥

**Comment by absidue** [comment]
If you are using a bundler like webpack, you can write your code with ES6 imports and use the web version, as long as you are only using YouTube.js in the renderer (the node version of YouTube.js needs linkedom as a DOM polyfil, which is not needed in web browsers or the Electron renderer process).

That's what we do for FreeTube, also comes with the addional benefit of a smaller app size.

https://github.com/FreeTubeApp/FreeTube/blob/development/_scripts/webpack.renderer.config.js#L137

**Comment by Araxeus** [comment]
We are not using a bundler, and we are using YouTube.js from the main process

This definitely needs fixing anyway

**Comment by Araxeus** [comment]
> I recommend bundling your code,

Thanks for the tip, but it has nothing to do with the issue here (or loading from renderer vs main) 😅

**Comment by Araxeus** [comment]
> This is interesting. I wonder what's happening to the package.json file for it to fail like that.

I think it's because the app is inside a https://github.com/electron/asar file, so `readFileSync` fails

**Comment by Araxeus** [comment]
@LuanRT Ok sorry but I was completely wrong, it reads the package.json file correctly, but it's missing fields somehow...

```
{
  dirname: 'C:\\Users\\Araxeus\\AppData\\Local\\Programs\\youtube-music\\resources\\app.asar\\node_modules\\youtubei.js\\bundle',
  full_path: 'C:\\Users\\Araxeus\\AppData\\Local\\Programs\\youtube-music\\resources\\app.asar\\node_modules\\youtubei.js\\package.json',
  package_json: {
    name: 'youtubei.js',
    version: '3.1.1',
    description: "A wrapper around YouTube's private API. Supports YouTube, YouTube Music, YouTube Kids and YouTube Studio (WIP).",
    type: 'module',
    types: './dist/src/platform/lib.d.ts',
    typesVersions: { '*': [Object] },
    exports: {
      './bundle': './bundle/node.cjs',
      '.': [Object],
      './agnostic': [Object],
      './web': [Object],
      './web.bundle': [Object],
      './web.bundle.min': [Object]
    },
    author: 'LuanRT <luan.lrt4@gmail.com> (https://github.com/LuanRT)',
    funding: [ 'https://github.com/sponsors/LuanRT' ],
    directories: { test: './test', examples: './examples', dist: './dist' },
    repository: {
      type: 'git',
      url: 'git+https://github.com/LuanRT/YouTube.js.git'
    },
    license: 'MIT',
    dependencies: { jintr: '^0.4.1', linkedom: '^0.14.12', undici: '^5.19.1' },
    devDependencies: {
      '@types/jest': '^28.1.7',
      '@types/node': '^17.0.45',
      '@typescript-eslint/eslint-plugin': '^5.30.6',
      'cpy-cli': '^4.2.0',
      esbuild: '^0.14.49',
      eslint: '^8.19.0',
      'eslint-plugin-tsdoc': '^0.2.16',
      glob: '^8.0.3',
      jest: '^28.1.3',
      pbkit: '^0.0.59',
      replace: '^1.2.2',
      'ts-jest': '^28.0.8',
      typescript: '^4.9.5'
    },
    homepage: 'https://github.com/LuanRT/YouTube.js#readme'
  }
}
```

and then https://github.com/LuanRT/YouTube.js/blob/1c72a41675e47f711bd61ebb898bca5527406a79/src/platform/node.ts#L102-L107 

Accesses `package.bugs.url` but `package.bugs` is undefined so it throws an error

**Comment by Araxeus** [comment]
This is extremely weird, I don't know what to think... 

what could ever cause the package.json to get so short like that? 😣

**Comment by absidue** [comment]
That only fixes the crash, it doesn't actually solve the fundemental issue of the properties not being there.

**Comment by LuanRT** [comment]
@Araxeus 
Do you know if the `homepage` field is always there? If it is, then it would be a good idea to use that as a fallback for the bugs url. Similar to what's being done in the `repo_url` field. This way, we could keep it.

Anywho, it's still weird how the bug report URL is missing in `package.json`.
