### ISSUE TITLE
v1.4.2 Crash with async WebSockets

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#39]
## Expected Behavior
I tried building a WebSockets server for this library. The idea was to include it in the app, start it, and use WebSockets to communicate with QML UI. I'm really inexperienced, so please forgive me for asking stupid questions and taking time. I've read some information online and couldn't find any answers.

## Current Behavior
It crashes with the following error:

## Failure Information (for bugs)
```
/home/stas/youtube-js-server/node_modules/youtubei.js/lib/Innertube.js:44
  async #init() {
             ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/stas/youtube-js-server/node_modules/youtubei.js/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
[Source code](https://github.com/LuanRT/YouTube.js/files/8571954/youtube-js-web.zip)

## Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information

**Comment by LuanRT** [comment]
That is happening because you're using an older version of node, [see this](https://github.com/LuanRT/YouTube.js#prerequisites) for more info.

**Comment by walking-octopus** [comment]
Thanks! It was NVM all along. BTW, how do you feel about your library being used for a custom YT client for Linux phones? Was it created more for automation or custom frontends?

I also just wanted to thank you for building and maintaining this project. I always had some ideas for building cool things with YouTube API but was always met with Google's limitations. Thanks for building a better YouTube API than Google ever did.
