### ISSUE TITLE
CompactMovie not found!

### ISSUE THREAD

**Issue by inad9300** [LuanRT/YouTube.js#460]
InnertubeError: CompactMovie not found!
This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!
Introspected and JIT generated this class in the meantime:
```js
class CompactMovie extends YTNode {
  static type = 'CompactMovie';

  video_id: string;
  thumbnail: Thumbnail[];
  title: Text;
  length_text: Text;
  endpoint: NavigationEndpoint;
  badges: ObservedArray<YTNodes.MetadataBadge> | null;
  menu: YTNodes.Menu | null;
  use_vertical_poster: boolean;
  top_metadata_items: {
    0: Text
  };
  thumbnail_overlays: ObservedArray<YTNodes.ThumbnailOverlayTimeStatus | YTNodes.ThumbnailOverlayToggleButton | YTNodes.ThumbnailOverlayNowPlaying> | null;
  author: Author;

  constructor(data: RawNode) {
    super();
    this.video_id = data.videoId;
    this.thumbnail = Thumbnail.fromResponse(data.thumbnail);
    this.title = new Text(data.title);
    this.length_text = new Text(data.lengthText);
    this.endpoint = new NavigationEndpoint(data.navigationEndpoint);
    this.badges = Parser.parse(data.badges, true, [ YTNodes.MetadataBadge ]);
    this.menu = Parser.parseItem(data.menu, [ YTNodes.Menu ]);
    this.use_vertical_poster = data.useVerticalPoster;
    this.top_metadata_items = {
      0: new Text(data.topMetadataItems.0)
    };
    this.thumbnail_overlays = Parser.parse(data.thumbnailOverlays, true, [ YTNodes.ThumbnailOverlayTimeStatus, YTNodes.ThumbnailOverlayToggleButton, YTNodes.ThumbnailOverlayNowPlaying ]);
    this.author = new Author(data.shortBylineText, undefined);
  }
}
```

```sh
    at YTNodeGenerator._YTNodeGenerator_logNewClass (file:///Users/danielma/Projects/captain-caption/scripts/node_modules/youtubei.js/dist/src/parser/generator.js:508:18)
    at YTNodeGenerator.createRuntimeClass (file:///Users/danielma/Projects/captain-caption/scripts/node_modules/youtubei.js/dist/src/parser/generator.js:166:77)
    at YTNodeGenerator.generateRuntimeClass (file:///Users/danielma/Projects/captain-caption/scripts/node_modules/youtubei.js/dist/src/parser/generator.js:231:30)
    at Parser.parseItem (file:///Users/danielma/Projects/captain-caption/scripts/node_modules/youtubei.js/dist/src/parser/parser.js:225:106)
    at Parser.parseArray (file:///Users/danielma/Projects/captain-caption/scripts/node_modules/youtubei.js/dist/src/parser/parser.js:249:37)
    at new TwoColumnWatchNextResults (file:///Users/danielma/Projects/captain-caption/scripts/node_modules/youtubei.js/dist/src/parser/classes/TwoColumnWatchNextResults.js:15:41)
    at Parser.parseItem (file:///Users/danielma/Projects/captain-caption/scripts/node_modules/youtubei.js/dist/src/parser/parser.js:234:32)
    at Parser.parse (file:///Users/danielma/Projects/captain-caption/scripts/node_modules/youtubei.js/dist/src/parser/parser.js:278:43)
    at Parser.parseResponse (file:///Users/danielma/Projects/captain-caption/scripts/node_modules/youtubei.js/dist/src/parser/parser.js:36:31)
    at new MediaInfo (file:///Users/danielma/Projects/captain-caption/scripts/node_modules/youtubei.js/dist/src/core/mixins/MediaInfo.js:17:137) {
  date: 2023-07-31T17:33:31.623Z,
  version: '5.8.0'
}
```

### Checklist

- [ ] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by fabcotech** [comment]
I have this bug as well, the following script reproduces it `"youtubei.js": "^5.8.0"`, the error message also contains `ProductListItem not found!`, `Something went wrong at ProductList!` and others

```js
const { Innertube } = require("youtubei.js");

const f = async () => {
  const it = await Innertube.create({
    /* setup - see above */
  });
  const videoInfo = await it.getInfo("ADjB99cgrrM");
};
f();
```

**Comment by LuanRT** [comment]
These warnings are mostly harmless. It's just the parser telling you something's new/changed. Either way, I guess we should add a way to disable them.

**Comment by fabcotech** [comment]
Thanks, I got it now, the problem for me is that I am running this script as a child process, the child process must return/console.log `stdout` a string **that is valid json** . If `youtubei.js` console.logs stuffs, then my main process will be incapable of JSON.parsing the result from the child process ;) . Yes we need a way to disable them.

For now I can probably find a workaround in my code.
