### ISSUE TITLE
9971ffe InnertubeError: Something went wrong at ClipSection!

### ISSUE THREAD

**Issue by RfadnjdExt** [LuanRT/YouTube.js#472]
### Steps to reproduce

```ts
await yt.getInfo(videoId)
```

### Failure Logs

```shell
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at Parser._Parser_printError (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/parser.js:401:18)
    at Parser.parseItem (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/parser.js:239:77)
    at new EngagementPanelSectionList (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/classes/EngagementPanelSectionList.js:12:31)
    at Parser.parseItem (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/parser.js:234:32)
    at file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/parser.js:200:31
    at Array.map (<anonymous>)
    at Parser.parseResponse (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/parser.js:199:104)
    at new MediaInfo (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/core/mixins/MediaInfo.js:17:137)
    at new VideoInfo (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/youtube/VideoInfo.js:36:9)
    at Innertube.<anonymous> (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/Innertube.js:75:20) {
  info: {
    stack: 'Error: Type mismatch, got ClipSection but expected one of SectionList, ContinuationItem, StructuredDescriptionContent, MacroMarkersList\n' +
      '    at Parser.parseItem (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/parser.js:229:35)\n' +
      '    at new EngagementPanelSectionList (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/classes/EngagementPanelSectionList.js:12:31)\n' +
      '    at Parser.parseItem (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/parser.js:234:32)\n' +
      '    at file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/parser.js:200:31\n' +
      '    at Array.map (<anonymous>)\n' +
      '    at Parser.parseResponse (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/parser.js:199:104)\n' +
      '    at new MediaInfo (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/core/mixins/MediaInfo.js:17:137)\n' +
      '    at new VideoInfo (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/parser/youtube/VideoInfo.js:36:9)\n' +
      '    at Innertube.<anonymous> (file:///workspaces/yurasubs-stream/node_modules/youtubei.js/dist/src/Innertube.js:75:20)\n' +
      '    at Generator.next (<anonymous>)'
  },
  date: 2023-08-13T07:14:55.571Z,
  version: '5.8.0'
}
```

### Expected behavior

No error.

### Current behavior

Full of error even though the data is returned correctly.

### Version

Edge

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by ChunkyProgrammer** [comment]
What video gave you this error?

**Comment by RfadnjdExt** [comment]
> What video gave you this error?

The error occurred when calling the `yt.getInfo(videoId)` function. However, this issue seems to be affecting multiple videos, not just a specific one. The error message points to a type mismatch involving `ClipSection`. It's consistently happening across various videos despite the data being returned correctly. If you need further information, please let me know. Thank you for your assistance!

**Comment by absidue** [comment]
Having specific videos to test with would be useful.

**Comment by JellyBrick** [comment]
Test video: https://www.youtube.com/watch?v=YsSShYaKOvk

This error is caused when using a `YouTube Premium` user's cookie.
