### ISSUE TITLE
5.8.0 InnertubeError: Something went wrong at Button!

### ISSUE THREAD

**Issue by short443** [LuanRT/YouTube.js#477]
### Steps to reproduce

Sometimes, when my users are searching using the query system, they encounter the error "InnertubeError: Something went wrong at Button!" I haven't noticed a pattern, but my parameters are as follows:

const youtube = await Innertube.create({
	lang: "pt-BR",
	location: "BR",
	cookie: process.env.COOKIES,
	generate_session_locally: true
});

...

const filters = {
	sort_by: "relevance"
};

const searchResult = await youtube.search(queryYT.toLowerCase(), filters);

	const videos = searchResult.results
	.filter(result => result.type === 'Video')
	.map(video => ({
		id: video.id,
		title: video.title.runs[0].text,
		author: video.author.name,
		authorId: video.author.id,
		duration: video.duration.text
	}));

### Failure Logs

```shell
InnertubeError: Something went wrong at Button!
 This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
     at Parser._Parser_printError (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:401:18)
     at Parser.parseItem (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:239:77)
     at new BackstagePost (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/classes/BackstagePost.js:31:39)
     at new Post (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/classes/Post.js:4:9)
     at Parser.parseItem (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:234:32)
     at Parser.parseArray (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:249:37)
     at new HorizontalList (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/classes/HorizontalList.js:7:29)
     at Parser.parseItem (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:234:32)
     at new Shelf (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/classes/Shelf.js:13:31)
     at Parser.parseItem (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:234:32) {
   info: {
     stack: 'Error: Type mismatch, got Button but expected CommentActionButtons\n' +
       '    at Parser.parseItem (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:232:31)\n' +
       '    at new BackstagePost (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/classes/BackstagePost.js:31:39)\n' +
       '    at new Post (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/classes/Post.js:4:9)\n' +
       '    at Parser.parseItem (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:234:32)\n' +
       '    at Parser.parseArray (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:249:37)\n' +
       '    at new HorizontalList (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/classes/HorizontalList.js:7:29)\n' +
       '    at Parser.parseItem (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:234:32)\n' +
       '    at new Shelf (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/classes/Shelf.js:13:31)\n' +
       '    at Parser.parseItem (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:234:32)\n' +
       '    at Parser.parseArray (file:///home/ubuntu/project/node_modules/youtubei.js/dist/src/parser/parser.js:249:37)'
   },
   date: 2023-08-22T23:24:38.603Z,
   version: '5.8.0'
 }
```

### Expected behavior

No error.

### Current behavior

Sometimes this error occurs:

InnertubeError: Something went wrong at Button!

It doesn't happen in every search, but it occurs quite frequently.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Fixed in https://github.com/LuanRT/YouTube.js/pull/499.
