### ISSUE TITLE
Error while retrieving Community Posts: `InnertubeError: Something went wrong at Video!`

### ISSUE THREAD

**Issue by nagalluri** [LuanRT/YouTube.js#515]
### Steps to reproduce

I am trying to retrieve community posts but I am consistently observing the below error. You should be able to reproduce with the following code snippet. Could you please provide details on how this could be resolved? Thanks

```
const { Innertube, UniversalCache } = require("youtubei.js");

const yt = await Innertube.create({ cache: new UniversalCache(false), generate_session_locally: true }); const channel = await yt.getChannel("UCWOA1ZGywLbqmigxE4Qlvuw");

console.info('\nCommunity posts:');
const posts = await channel.getCommunity();
```

### Failure Logs

```shell
InnertubeError: Something went wrong at Video!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at ERROR_HANDLER (/var/task/node_modules/youtubei.js/bundle/node.cjs:10325:22)
    at Object.parseItem (/var/task/node_modules/youtubei.js/bundle/node.cjs:10634:7)
    at new BackstagePost (/var/task/node_modules/youtubei.js/bundle/node.cjs:2523:40)
    at Object.parseItem (/var/task/node_modules/youtubei.js/bundle/node.cjs:10630:22)
    at new BackstagePostThread (/var/task/node_modules/youtubei.js/bundle/node.cjs:2536:32)
    at parseItem (/var/task/node_modules/youtubei.js/bundle/node.cjs:10630:22)
    at Object.parseArray (/var/task/node_modules/youtubei.js/bundle/node.cjs:10650:22)
    at new ItemSection (/var/task/node_modules/youtubei.js/bundle/node.cjs:6142:36)
    at parseItem (/var/task/node_modules/youtubei.js/bundle/node.cjs:10630:22)
    at Object.parseArray (/var/task/node_modules/youtubei.js/bundle/node.cjs:10650:22) {
  info: {
    stack: "TypeError: Cannot read properties of undefined (reading 'find')\n" +
      '    at new Video (/var/task/node_modules/youtubei.js/bundle/node.cjs:1265:64)\n' +
      '    at Object.parseItem (/var/task/node_modules/youtubei.js/bundle/node.cjs:10630:22)\n' +
      '    at new BackstagePost (/var/task/node_modules/youtubei.js/bundle/node.cjs:2523:40)\n' +
      '    at Object.parseItem (/var/task/node_modules/youtubei.js/bundle/node.cjs:10630:22)\n' +
      '    at new BackstagePostThread (/var/task/node_modules/youtubei.js/bundle/node.cjs:2536:32)\n' +
      '    at parseItem (/var/task/node_modules/youtubei.js/bundle/node.cjs:10630:22)\n' +
      '    at Object.parseArray (/var/task/node_modules/youtubei.js/bundle/node.cjs:10650:22)\n' +
      '    at new ItemSection (/var/task/node_modules/youtubei.js/bundle/node.cjs:6142:36)\n' +
      '    at parseItem (/var/task/node_modules/youtubei.js/bundle/node.cjs:10630:22)\n' +
      '    at Object.parseArray (/var/task/node_modules/youtubei.js/bundle/node.cjs:10650:22)'
  },
  date: 2023-10-02T00:17:23.641Z,
  version: '6.4.0'
```

### Expected behavior

The expected behavior is to retrieve the list of community posts

### Current behavior

The call to retrieve community posts is failing with the specified error

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
That's just a parser warning (which you can turn off if they bother you), it shouldn't cause the whole function to break. Are you able to access that "posts" variable or is there a hard error that prevents that?

**Comment by nagalluri** [comment]
Thanks for the quick response. Yes, it seems I can still access the `posts` variable. May I ask what may be causing the parser warning? Is it something that I need to handle?

**Comment by absidue** [comment]
YouTube making layout changes or renaming properties. In this case it looks like one of the community posts has a video embedded/linked and they've made changes to the `videoRenderer` object, so the parser is erroring when it tries to parse that video.

**Comment by nagalluri** [comment]
Got it, thanks for the details
