### ISSUE TITLE
2.9.0 InnertubeError: SearchHeader not found!

### ISSUE THREAD

**Issue by Revelts** [LuanRT/YouTube.js#522]
### Steps to reproduce

```
import { Request, RequestHandler, Response } from "express";
import { Innertube } from 'youtubei.js';
import { Cache } from "../cache";
import Video from "youtubei.js/dist/src/parser/classes/Video";

interface VideoSearchResult {
  id: string,
  title: string,
  thumbnail: string
  views: string
};

const cache = new Cache<VideoSearchResult[]>(parseInt(process.env.SEARCH_RESULTS_CACHE_TIME) || 1800);

export default async function handle(request: Request, response: Response): Promise<RequestHandler> {
  const keyword = request.body.keyword;

  if (!keyword) {
    response.status(400).json({
      error: 'keyword not provided'
    });
    return;
  }

  const cached = cache.get(keyword);

  if (cached) {
    response.status(200).json(cached);
    return;
  }

  const youtube = await Innertube.create();
  const search_results = await youtube.search(keyword);

  if (search_results) {
    const results = search_results.results.filter(result => result.type == 'Video' && !(result as Video).short_view_count.toString().includes('watch')).
      map((video: Video): VideoSearchResult => ({
        id: video.id,
        title: video.title.toString(),
        thumbnail: video.thumbnails[0].url,
        views: video.short_view_count.toString().replace('views', '')
      }));

    cache.set(keyword, results);
    response.status(200).json(results);
  } else {
    response.status(200).json([]);
  }
};
```

### Failure Logs

```shell
InnertubeError: SearchHeader not found!
This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!
    at Function._Parser_printError (/home/revelt/youtube-audio-player/node_modules/youtubei.js/dist/src/parser/index.js:299:29)
    at Function.parseItem (/home/revelt/youtube-audio-player/node_modules/youtubei.js/dist/src/parser/index.js:161:77)
    at Function.parse (/home/revelt/youtube-audio-player/node_modules/youtubei.js/dist/src/parser/index.js:205:53)
    at Function.parseResponse (/home/revelt/youtube-audio-player/node_modules/youtubei.js/dist/src/parser/index.js:71:45)
    at new Feed (/home/revelt/youtube-audio-player/node_modules/youtubei.js/dist/src/core/Feed.js:83:70)
    at new Search (/home/revelt/youtube-audio-player/node_modules/youtubei.js/dist/src/parser/youtube/Search.js:25:9)
    at Innertube.<anonymous> (/home/revelt/youtube-audio-player/node_modules/youtubei.js/dist/src/Innertube.js:90:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/revelt/youtube-audio-player/node_modules/youtubei.js/dist/src/Innertube.js:5:58)
    at runMicrotasks (<anonymous>) {
  info: {
    chipBar: { chipCloudRenderer: [Object] },
    searchFilterButton: { buttonRenderer: [Object] },
    trackingParams: 'CBAQiOoKIhMI28Hl4c_1gQMVmFmdCR2U-wsT'
  },
  date: 2023-10-14T13:16:48.600Z,
  version: '2.9.0'
}
```

### Expected behavior

Not throwing error

### Current behavior

Return video list.

### Version

Default

### Checklist

- [ ] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment]
Please upgrade to the latest version of YouTube.js, 6.4.1, instead of using a version that was released in January and therefore doesn't support more recent YouTube changes.
