### ISSUE TITLE
1.4.2-d.3: JSON.parse error on getting new instance 

### ISSUE THREAD

**Issue by shevernitskiy** [LuanRT/YouTube.js#55]
## Expected Behavior

Create new instace of Innertube without any error

## Current Behavior

Got error, while parsing json in SessionBuilder

## Failure Information (for bugs)
Logs:

```
2022-05-19T04:08:15.593234+00:00 app[worker.1]: undefined:1
2022-05-19T04:08:15.593235+00:00 app[worker.1]: undefined
2022-05-19T04:08:15.593236+00:00 app[worker.1]: ^
2022-05-19T04:08:15.593236+00:00 app[worker.1]:
2022-05-19T04:08:15.593237+00:00 app[worker.1]: SyntaxError: Unexpected token u in JSON at position 0
2022-05-19T04:08:15.593237+00:00 app[worker.1]: at JSON.parse (<anonymous>)
2022-05-19T04:08:15.593238+00:00 app[worker.1]: at SessionBuilder.#getYtConfig (/app/node_modules/youtubei.js/lib/core/SessionBuilder.js:79:17)
2022-05-19T04:08:15.593241+00:00 app[worker.1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)

2022-05-19T04:08:15.593241+00:00 app[worker.1]: at async Promise.all (index 0)
2022-05-19T04:08:15.593242+00:00 app[worker.1]: at async SessionBuilder.build (/app/node_modules/youtubei.js/lib/core/SessionBuilder.js:25:18)
2022-05-19T04:08:15.593244+00:00 app[worker.1]: at async Innertube.#init (/app/node_modules/youtubei.js/lib/Innertube.js:47:21)
2022-05-19T04:08:15.593244+00:00 app[worker.1]: at async file:///app/build/src/skills/youtube.js:19:28
2022-05-19T04:08:15.618562+00:00 app[worker.1]: error Command failed with exit code 1.
```

### Steps to Reproduce

I trying to do this

```ts
  private _client

  constructor() {
    super()
    ;(async () => {
      this._client = await new Innertube()
    })()
  }
  ```

### Failure Logs

Please include any relevant log snippets or files here.

## Checklist

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information

**Comment by LuanRT** [comment]
🤔 Weird, can you try accessing https://www.youtube.com/sw.js through a browser and see what it looks like? Maybe it is being blocked or returning something completely different.

**Comment by shevernitskiy** [comment]
This is logs from heroku. Locally, all works perfect, from browser too. Moreover, it worked on heroku till this moment.

I checked sw.js on heroku.
Axios got 200 repsonse whith this strange data:

```
2022-05-19T05:05:10.213426+00:00 app[worker.1]: data: '\n' +
2022-05-19T05:05:10.213427+00:00 app[worker.1]: "  self.addEventListener('install', event => {\n" +
2022-05-19T05:05:10.213427+00:00 app[worker.1]: '    event.waitUntil(self.skipWaiting());\n' +
2022-05-19T05:05:10.213427+00:00 app[worker.1]: '  });\n' +
2022-05-19T05:05:10.213427+00:00 app[worker.1]: "  self.addEventListener('activate', event => {\n" +
2022-05-19T05:05:10.213427+00:00 app[worker.1]: '    event.waitUntil(\n' +
2022-05-19T05:05:10.213428+00:00 app[worker.1]: '      self.clients.claim().then(() => self.registration.unregister()));\n' +
2022-05-19T05:05:10.213428+00:00 app[worker.1]: '  });\n' +
2022-05-19T05:05:10.213428+00:00 app[worker.1]: '  '
2022-05-19T05:05:10.213429+00:00 app[worker.1]: }
```

I tried to make request with Useragent as well.

**Comment by shevernitskiy** [comment]
It seems like we can obtain api key from `https://www.youtube.com/sw.js_data`
And then fetch additional info from `https://www.youtube.com/youtubei/v1/notification_registration/set_registration?key={key}&prettyPrint=false` if needed.

I checked from heroku, this endpoints available

**Comment by LuanRT** [comment]
> It seems like we can obtain api key from `https://www.youtube.com/sw.js_data` 

I believe the service worker endpoint was acting up due to Heroku's IP/server location. But great findings, that should be a drop-in replacement for `/sw.js`, the notification registration endpoint won't be necessary though.

**Comment by shevernitskiy** [comment]
It works! Thanks for the rapid fix:)
