### ISSUE TITLE
9.2.0 Posts a comment with error 403

### ISSUE THREAD

**Issue by meghe2000** [LuanRT/YouTube.js#633]
### Steps to reproduce

import { ClientType, Innertube } from 'youtubei.js';

async function start() {
    const yt = await Innertube.create(
        {
            client_type: ClientType.WEB,
            cookie: "my browser cookie..."
        }
    );
    const vid = 'ZiplxPdOJd4';

    const com = await yt.interact.comment(vid, 'GOOD');
    console.log(com.data);
}

start();

### Failure Logs

```shell
node_modules/youtubei.js/dist/src/utils/HTTPClient.js:101
            throw new InnertubeError(`Request to ${response.url} failed with status ${response.status}`, yield response.text());
                  ^

InnertubeError: Request to https://www.youtube.com/youtubei/v1/comment/create_comment?prettyPrint=false&alt=json failed with status 403
    at HTTPClient.<anonymous> (node_modules/youtubei.js/dist/src/utils/HTTPClient.js:101:19)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules\tslib\tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  info: '{\n' +
    '  "error": {\n' +
    '    "code": 403,\n' +
    '    "message": "Comment failed to post.",\n' +
    '    "status": "PERMISSION_DENIED"\n' +
    '  }\n' +
    '}\n',
  date: 2024-04-10T12:53:30.800Z,
  version: '9.2.0'
}

Node.js v18.16.0
```

### Expected behavior

Send a comment and get the result.

### Current behavior

Not sending the comment while other functions like getHomeFeed works fine.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Works fine here, but I'm using OAuth. I do not recommend cookies because Google rotates them every 15 minutes or so. 

Also, you do not need the `client_type` param. The `WEB` client is used by default in most cases.

**Comment by meghe2000** [comment]
import { ClientType, Innertube, UniversalCache } from 'youtubei.js';

async function start() {
    const vid = 'ZiplxPdOJd4';
    const yt = await Innertube.create(
        {
            cache: new UniversalCache(true),
            generate_session_locally: true,
            client_type: ClientType.ANDROID,
        }
    );

    yt.session.on('auth-pending', (data) => {
        console.log(`Go to ${data.verification_url} in your browser and enter code ${data.user_code} to authenticate.`);
    });

    await yt.session.signIn();
    await yt.session.oauth.cacheCredentials();
    console.log((await yt.getHomeFeed()).contents.contents.length);
}


When I use OAuth there is no problem with ClientType.WEB, but when I use ClientType.ANDROID I get this error.

node_modules/youtubei.js/dist/src/utils/HTTPClient.js:101
            throw new InnertubeError(`Request to ${response.url} failed with status ${response.status}`, yield response.text());
                  ^

InnertubeError: Request to https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&alt=json failed with status 404
    at HTTPClient.<anonymous> (node_modules/youtubei.js/dist/src/utils/HTTPClient.js:101:19)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules\tslib\tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  info: '{\n' +
    '  "error": {\n' +
    '    "code": 404,\n' +
    '    "message": "Requested entity was not found.",\n' +
    '    "status": "NOT_FOUND"\n' +
    '  }\n' +
    '}\n',
  date: 2024-04-13T12:51:01.363Z,
  version: '9.2.0'
}

Node.js v18.16.0

**Comment by LuanRT** [comment]
In your case, there's no difference. `WEB` is just as fast as `ANDROID`.

**Comment by TechBroCode** [comment]
> ClientType.ANDROID is faster than WEB.
> 
> ```
> import { ClientType, Innertube, UniversalCache } from 'youtubei.js';
> 
> async function start() {
>     const vid = 'ZiplxPdOJd4';
>     const yt = await Innertube.create(
>         {
>             cache: new UniversalCache(true),
>             generate_session_locally: true,
>             client_type: ClientType.ANDROID,
>         }
>     );
> 
>     yt.session.on('auth-pending', (data) => {
>         console.log(`Go to ${data.verification_url} in your browser and enter code ${data.user_code} to authenticate.`);
>     });
> 
>     await yt.session.signIn();
>     await yt.session.oauth.cacheCredentials();
>     console.log((await yt.getHomeFeed()).contents.contents.length);
> }
> ```
> 
> When I use OAuth there is no problem with ClientType.WEB, but when I use ClientType.ANDROID I get this error.
> 
> ```
> node_modules/youtubei.js/dist/src/utils/HTTPClient.js:101
>             throw new InnertubeError(`Request to ${response.url} failed with status ${response.status}`, yield response.text());
>                   ^
> 
> InnertubeError: Request to https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&alt=json failed with status 404
>     at HTTPClient.<anonymous> (node_modules/youtubei.js/dist/src/utils/HTTPClient.js:101:19)
>     at Generator.next (<anonymous>)
>     at fulfilled (node_modules\tslib\tslib.js:166:62)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   info: '{\n' +
>     '  "error": {\n' +
>     '    "code": 404,\n' +
>     '    "message": "Requested entity was not found.",\n' +
>     '    "status": "NOT_FOUND"\n' +
>     '  }\n' +
>     '}\n',
>   date: 2024-04-13T12:51:01.363Z,
>   version: '9.2.0'
> }
> ```
> 
> Node.js v18.16.0

I just made use of WEB and it was successful.

**Comment by TechBroCode** [comment]
> In your case, there's no difference. `WEB` is just as fast as `ANDROID`.

How do i clear the cached credentials? Take for instance if i'm  switching accounts
