### ISSUE TITLE
9.4.0 - TypeError: Cannot read properties of undefined (reading 'lightTheme')

### ISSUE THREAD

**Issue by Lcstyle** [LuanRT/YouTube.js#653]
### Steps to reproduce

updated to 9.4.0

### Failure Logs

```shell
[YOUTUBEJS][Parser]: InnertubeError: Something went wrong at CollectionThumbnailView!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at ERROR_HANDLER (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:48:31)
    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:393:13)
    at new LockupView (file:///root/node_modules/youtubei.js/dist/src/parser/classes/LockupView.js:9:37)
    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at new RichItem (file:///root/node_modules/youtubei.js/dist/src/parser/classes/RichItem.js:6:31)
    at parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at Module.parseArray (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)
    at new RichGrid (file:///root/node_modules/youtubei.js/dist/src/parser/classes/RichGrid.js:9:32)
    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at new Tab (file:///root/node_modules/youtubei.js/dist/src/parser/classes/Tab.js:13:31) {
  info: {
    stack: "TypeError: Cannot read properties of undefined (reading 'lightTheme')\n" +
      '    at new CollectionThumbnailView (file:///root/node_modules/youtubei.js/dist/src/parser/classes/CollectionThumbnailView.js:9:42)\n' +
      '    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new LockupView (file:///root/node_modules/youtubei.js/dist/src/parser/classes/LockupView.js:9:37)\n' +
      '    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new RichItem (file:///root/node_modules/youtubei.js/dist/src/parser/classes/RichItem.js:6:31)\n' +
      '    at parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at Module.parseArray (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)\n' +
      '    at new RichGrid (file:///root/node_modules/youtubei.js/dist/src/parser/classes/RichGrid.js:9:32)\n' +
      '    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new Tab (file:///root/node_modules/youtubei.js/dist/src/parser/classes/Tab.js:13:31)'
  },
  date: 2024-04-29T15:37:37.262Z,
  version: '9.4.0'

```
```


### Expected behavior

no exception

### Current behavior

using yt2alt

### Version

Default

### Anything else?

_No response_

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by Lcstyle** [comment]
also:

```
[YOUTUBEJS][Parser]: InnertubeError: Something went wrong at ThumbnailView!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at ERROR_HANDLER (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:48:31)
    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:393:13)
    at new CollectionThumbnailView (file:///root/node_modules/youtubei.js/dist/src/parser/classes/CollectionThumbnailView.js:7:41)
    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at new LockupView (file:///root/node_modules/youtubei.js/dist/src/parser/classes/LockupView.js:9:37)
    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at new RichItem (file:///root/node_modules/youtubei.js/dist/src/parser/classes/RichItem.js:6:31)
    at parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at Module.parseArray (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)
    at new RichGrid (file:///root/node_modules/youtubei.js/dist/src/parser/classes/RichGrid.js:9:32) {
  info: {
    stack: "TypeError: Cannot read properties of undefined (reading 'lightTheme')\n" +
      '    at new ThumbnailView (file:///root/node_modules/youtubei.js/dist/src/parser/classes/ThumbnailView.js:12:47)\n' +
      '    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new CollectionThumbnailView (file:///root/node_modules/youtubei.js/dist/src/parser/classes/CollectionThumbnailView.js:7:41)\n' +
      '    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new LockupView (file:///root/node_modules/youtubei.js/dist/src/parser/classes/LockupView.js:9:37)\n' +
      '    at Module.parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new RichItem (file:///root/node_modules/youtubei.js/dist/src/parser/classes/RichItem.js:6:31)\n' +
      '    at parseItem (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at Module.parseArray (file:///root/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)\n' +
      '    at new RichGrid (file:///root/node_modules/youtubei.js/dist/src/parser/classes/RichGrid.js:9:32)'
  },
  date: 2024-04-29T15:36:17.454Z,
  version: '9.4.0'

```

**Comment by iBicha** [comment]
Fixed in https://github.com/LuanRT/YouTube.js/pull/686
