### ISSUE TITLE
10.0.0 [YOUTUBEJS][Parser]: InnertubeError: Something went wrong at ThumbnailBadgeView/ThumbnailView/CollectionThumbnailView!

### ISSUE THREAD

**Issue by iBicha** [LuanRT/YouTube.js#684]
### Steps to reproduce

I just ran `npx yt2alt` (https://github.com/iBicha/yt2alt)
Happens when calling
```
        const feed = await this.innertube.getPlaylists();

        let playlists = feed.playlists;

        while (feed.has_continuation) {
            try {
                feed = await feed.getContinuation();
                playlists.push(...feed.playlists);
            } catch (error) {
                console.error(error);
                break;
            }
        }
```

### Failure Logs

```shell
[YOUTUBEJS][Parser]: InnertubeError: Something went wrong at ThumbnailBadgeView!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at ERROR_HANDLER (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:48:31)
    at parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:393:13)
    at Module.parseArray (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)
    at new ThumbnailOverlayBadgeView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/ThumbnailOverlayBadgeView.js:7:30)
    at parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at Module.parseArray (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)
    at new ThumbnailView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/ThumbnailView.js:10:32)
    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at new CollectionThumbnailView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/CollectionThumbnailView.js:7:41)
    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28) {
  info: {
    stack: "TypeError: Cannot read properties of undefined (reading 'lightTheme')\n" +
      '    at new ThumbnailBadgeView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/ThumbnailBadgeView.js:9:47)\n' +
      '    at parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at Module.parseArray (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)\n' +
      '    at new ThumbnailOverlayBadgeView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/ThumbnailOverlayBadgeView.js:7:30)\n' +
      '    at parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at Module.parseArray (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)\n' +
      '    at new ThumbnailView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/ThumbnailView.js:10:32)\n' +
      '    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new CollectionThumbnailView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/CollectionThumbnailView.js:7:41)\n' +
      '    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)'
  },
  date: 2024-07-10T21:37:57.336Z,
  version: '10.0.0'
}
[YOUTUBEJS][Parser]: InnertubeError: Something went wrong at ThumbnailView!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at ERROR_HANDLER (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:48:31)
    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:393:13)
    at new CollectionThumbnailView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/CollectionThumbnailView.js:7:41)
    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at new LockupView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/LockupView.js:9:37)
    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at new RichItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/RichItem.js:6:31)
    at parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at Module.parseArray (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)
    at new RichGrid (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/RichGrid.js:9:32) {
  info: {
    stack: "TypeError: Cannot read properties of undefined (reading 'lightTheme')\n" +
      '    at new ThumbnailView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/ThumbnailView.js:12:47)\n' +
      '    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new CollectionThumbnailView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/CollectionThumbnailView.js:7:41)\n' +
      '    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new LockupView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/LockupView.js:9:37)\n' +
      '    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new RichItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/RichItem.js:6:31)\n' +
      '    at parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at Module.parseArray (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)\n' +
      '    at new RichGrid (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/RichGrid.js:9:32)'
  },
  date: 2024-07-10T21:37:57.340Z,
  version: '10.0.0'
}
[YOUTUBEJS][Parser]: InnertubeError: Something went wrong at CollectionThumbnailView!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at ERROR_HANDLER (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:48:31)
    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:393:13)
    at new LockupView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/LockupView.js:9:37)
    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at new RichItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/RichItem.js:6:31)
    at parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at Module.parseArray (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)
    at new RichGrid (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/RichGrid.js:9:32)
    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)
    at new Tab (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/Tab.js:13:31) {
  info: {
    stack: "TypeError: Cannot read properties of undefined (reading 'lightTheme')\n" +
      '    at new CollectionThumbnailView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/CollectionThumbnailView.js:9:42)\n' +
      '    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new LockupView (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/LockupView.js:9:37)\n' +
      '    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new RichItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/RichItem.js:6:31)\n' +
      '    at parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at Module.parseArray (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:408:28)\n' +
      '    at new RichGrid (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/RichGrid.js:9:32)\n' +
      '    at Module.parseItem (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/parser.js:388:28)\n' +
      '    at new Tab (file:///Users/path/to/yt2alt/node_modules/youtubei.js/dist/src/parser/classes/Tab.js:13:31)'
  },
  date: 2024-07-10T21:37:57.341Z,
  version: '10.0.0'
}
```

### Expected behavior

No errors

### Current behavior

Errors

### Version

Default

### Checklist

- [ ] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by iBicha** [comment]
Duplicate of https://github.com/LuanRT/YouTube.js/issues/653
