### ISSUE TITLE
[10.1.0] The server responded with a non 2xx status code

### ISSUE THREAD

**Issue by binbard** [LuanRT/YouTube.js#700]
### Steps to reproduce
```

import { ClientType, Innertube, UniversalCache, Utils } from 'youtubei.js';
import { existsSync, mkdirSync, createWriteStream } from 'fs';

(async () => {
  const yt = await Innertube.create({ cache: new UniversalCache(false), generate_session_locally: true, client_type: ClientType.DESKTOP, request_options: { headers: { 'user-agent': 'Mozilla/5.0' } } });

  const songId = 'tLTHjpxTV4c'
  const stream = await yt.download(songId, {
    type: 'audio', // audio, video or video+audio
    quality: 'best', // best, bestefficiency, 144p, 240p, 480p, 720p and so on.
    format: 'mp4' // media container format 
  });

  console.info(`Downloading (${songId})`);

  const dir = `./mysongs`;

  if (!existsSync(dir)) {
    mkdirSync(dir);
  }

  const file = createWriteStream(`${dir}/${songId}.m4a`);

  for await (const chunk of Utils.streamToIterable(stream)) {
    file.write(chunk);
  }

  console.info(`${songId} - Done!`, '\n');
})();
```

### Failure Logs

```shell
file:///D:/doe/try/my/yt2/node_modules/youtubei.js/dist/src/utils/FormatUtils.js:61
                            throw new InnertubeError('The server responded with a non 2xx status code', { error_type: 'FETCH_FAILED', response });
                                  ^

InnertubeError: The server responded with a non 2xx status code
    at Module.<anonymous> (file:///D:/doe/try/my/yt2/node_modules/youtubei.js/dist/src/utils/FormatUtils.js:61:35)
    at Generator.next (<anonymous>)
    at fulfilled (D:\doe\try\my\yt2\node_modules\tslib\tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  info: {
    error_type: 'FETCH_FAILED',
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: {
        aborted: false,
        rangeRequested: false,
        timingAllowPassed: true,
        requestIncludesCredentials: true,
        type: 'default',
        status: 403,
        timingInfo: {
          startTime: 2261.644,
          redirectStartTime: 0,
          redirectEndTime: 0,
          postRedirectStartTime: 2261.644,
          finalServiceWorkerStartTime: 0,
          finalNetworkResponseStartTime: 0,
          finalNetworkRequestStartTime: 0,
          endTime: 2324.2184,
          encodedBodySize: 0,
          decodedBodySize: 0,
          finalConnectionTimingInfo: null
        },
        cacheState: '',
        statusText: 'Forbidden',
        headersList: HeadersList {
          cookies: null,
          [Symbol(headers map)]: Map(13) {
            'last-modified' => [Object],
            'content-type' => [Object],
            'content-length' => [Object],
            'connection' => [Object],
            'access-control-allow-origin' => [Object],
            'access-control-allow-credentials' => [Object],
            'timing-allow-origin' => [Object],
            'access-control-expose-headers' => [Object],
            'vary' => [Object],
            'cross-origin-resource-policy' => [Object],
            'x-content-type-options' => [Object],
            'date' => [Object],
            'server' => [Object]
          },
          [Symbol(headers map sorted)]: null
        },
        urlList: [ URL {} ],
        body: {
          stream: ReadableStream {
            [Symbol(kType)]: 'ReadableStream',
            [Symbol(kState)]: [Object],
            [Symbol(nodejs.webstream.isClosedPromise)]: [Object],
            [Symbol(nodejs.webstream.controllerErrorFunction)]: [Function: bound error]
          }
        }
      },
      [Symbol(headers)]: Headers {
        [Symbol(guard)]: 'immutable',
        [Symbol(headers list)]: HeadersList {
          cookies: null,
          [Symbol(headers map)]: Map(13) {
            'last-modified' => [Object],
            'content-type' => [Object],
            'content-length' => [Object],
            'connection' => [Object],
            'access-control-allow-origin' => [Object],
            'access-control-allow-credentials' => [Object],
            'timing-allow-origin' => [Object],
            'access-control-expose-headers' => [Object],
            'vary' => [Object],
            'cross-origin-resource-policy' => [Object],
            'x-content-type-options' => [Object],
            'date' => [Object],
            'server' => [Object]
          },
          [Symbol(headers map sorted)]: null
        },
        [Symbol(realm)]: null
      }
    }
  },
  date: 2024-07-25T11:47:17.548Z,
  version: '10.1.0'
}

Node.js v20.15.0
```

### Expected behavior

Should have downloaded 

### Current behavior

Not downloading only can list

### Version

Default

### Anything else?

"youtubei.js": "^10.1.0"

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by binbard** [comment]
@LuanRT What is the problem?
Is it specific to me?

**Comment by LuanRT** [comment]
@binbard 
This has already been fixed. Please see https://github.com/LuanRT/YouTube.js/pull/688.

**Comment by twicer-is-coder** [comment]
This issue is not fixed. Still happening.

**Comment by LuanRT** [comment]
If it's still happening feel free to open a new issue. This one is most likely unrelated to whatever is happening now (YouTube blocking your IPs, expecting attestation tokens, etc).

**Comment by stri8ed** [comment]
Noticed this error was caused by using `type: 'audio'`. When I change to `video+audio`, it works fine. It seems attempting to download audio track results in a 403.
