### ISSUE TITLE
10.3.0 - Can no longer getInfo

### ISSUE THREAD

**Issue by EliTheDev** [LuanRT/YouTube.js#722]
## Example:
1. Get channel info
```js
const { Innertube } = require("youtubei.js");
(async () => {
    const youtube = await new Innertube();
    const channel = await youtube.getChannel('UCgAZ8TVwkH_gUH_rVbrunaA');
    console.log(channel);
})();
```

### Failure Logs

```shell
C:\Coding\Utilities\youtubeijs\node_modules\youtubei.js\bundle\node.cjs:19227
    return (0, import_tslib66.__classPrivateFieldGet)(this, _Innertube_session, "f").actions;
                                                                                    ^

TypeError: Cannot read properties of undefined (reading 'actions')
    at get actions [as actions] (C:\Coding\Utilities\youtubeijs\node_modules\youtubei.js\bundle\node.cjs:19227:85)
    at Innertube.<anonymous> (C:\Coding\Utilities\youtubeijs\node_modules\youtubei.js\bundle\node.cjs:19138:35)
    at Generator.next (<anonymous>)
    at C:\Coding\Utilities\youtubeijs\node_modules\tslib\tslib.js:169:75
    at new Promise (<anonymous>)
    at __awaiter (C:\Coding\Utilities\youtubeijs\node_modules\tslib\tslib.js:165:16)
    at Innertube.getChannel (C:\Coding\Utilities\youtubeijs\node_modules\youtubei.js\bundle\node.cjs:19136:41)
    at C:\Coding\Utilities\youtubeijs\channel.js:4:35

Node.js v21.7.1
```

### Expected behavior

Respond with channel info.

### Current behavior

Gives module error. 

### Version

Default

### Anything else?

The same code was working a couple days ago.

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
From the readme:
```ts
// const { Innertube } = require('youtubei.js');
import { Innertube } from 'youtubei.js';
const youtube = await Innertube.create(/* options */);
```
