### ISSUE TITLE
10.3.0 Unable to download anything

### ISSUE THREAD

**Issue by gbarton** [LuanRT/YouTube.js#733]
### Steps to reproduce

For a few weeks now I have been unable to download anything at all.  I am on the latest 10.3.0 release.

Below is code snippets, but all of it can be found here: https://github.com/gbarton/yt4kids/blob/main/src/lib/yt/Downloader.ts#L135

```typescript
let yt : Innertube;


async function getYT(): Promise<Innertube> {
  // TODO: support testing by returning a mock one
  if (Utils.isNull(yt) || initialized === false) {
    yt = await Innertube.create({ client_type : ClientType.WEB/* options */});
  }
  return yt;
}

async function download(id: string, dlObj: DLOpts, path: string) {
  log.info(dlObj, "Download Options");
  const yt = await getYT();
 
  const stream = await Utils.cancellable<ReadableStream<Uint8Array>>(() => yt.download(id, dlObj), 5000);

  const file = createWriteStream(path);
  let chunks = 0;
  try {
    let percent = 0;
    const total = dlObj.contentLength;
  
    log.info(`aquired stream for video ${id}`);
  
    const bytesOnDisk = await Utils.cancellable<number>(async (): Promise<number> => {
        // need to wait on the write to ensure the file is completely ready
        for await (const chunk of YTTools.streamToIterable(stream)) {
          const p = new Promise((resolve, reject) => {
            file.write(chunk, (err) => {
              if (err) {
                log.error(err, "stream error");
                return reject(err);
              }
              return resolve(path);
            });
          });
          await p;
          chunks += chunk.length;
          if (Math.round(chunks / total * 100) >= percent + 10.0) {
            percent = Math.round(chunks / total * 100);
            log.info(`${percent}% (${chunks}/${total})`);
          }
        }
        
        percent = Math.round(chunks / total * 100);
        log.info(`${percent}% ${path} chunks written ${chunks}/${total}`);
        file.end();
        // file.close();
        return getFilesizeInBytes(path);
  
    }, 1000 * 60 * 10); // 10m timeout
    log.info(`bytes on disk: ${bytesOnDisk}/${total}`)
  } catch (err) {
    log.warn(`unable to download file, cleaning up ${chunks} bytes`);
    if(file) {
      file.end();
    }
    // clean up if we were partly through a file dl when we errored
    if (existsSync(path)) {
      rm(path);
    }
    throw err;
  }
}

```

### Failure Logs

```shell
With no options in the YT config I get the following error for any video attempt:

[19:19:25.431] ERROR (726001): The server responded with a non 2xx status code
    err: {
      "type": "InnertubeError",
      "message": "The server responded with a non 2xx status code",
      "stack":
          Error: The server responded with a non 2xx status code
              at Object.<anonymous> (/workspaces/yt4kids/node_modules/youtubei.js/src/utils/FormatUtils.ts:95:19)
              at Generator.next (<anonymous>)
              at fulfilled (/workspaces/yt4kids/node_modules/tslib/tslib.js:166:62)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
      "info": {
        "error_type": "FETCH_FAILED",
        "response": {}
      },
      "date": "2024-08-12T19:19:25.294Z",
      "version": "10.3.0"
    }

If I try adding `{ client_type : ClientType.ANDROID}`, or `IOS`, or `TV_EMBEDDED`, I get different errors when attempting to download:

[19:17:37.114] ERROR (725473): Request to https://www.youtube.com/youtubei/v1/player?prettyPrint=false&alt=json failed with status 404
    err: {
      "type": "InnertubeError",
      "message": "Request to https://www.youtube.com/youtubei/v1/player?prettyPrint=false&alt=json failed with status 404",
      "stack":
          Error: Request to https://www.youtube.com/youtubei/v1/player?prettyPrint=false&alt=json failed with status 404
              at HTTPClient.<anonymous> (/workspaces/yt4kids/node_modules/youtubei.js/src/utils/HTTPClient.ts:165:11)
              at Generator.next (<anonymous>)
              at fulfilled (/workspaces/yt4kids/node_modules/tslib/tslib.js:166:62)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
      "info": "{\n  \"error\": {\n    \"code\": 404,\n    \"message\": \"Requested entity was not found.\",\n    \"status\": \"NOT_FOUND\"\n  }\n}\n",
      "date": "2024-08-12T19:17:37.114Z",
      "version": "10.3.0"
    }

So it looks like only the WEB client type is supported anymore?  But for me the web client type is getting non 2xx response codes no matter what video it is.
```

### Expected behavior

Video's to be downloaded when used

### Current behavior

the above stacktraces. :(

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by lovegaoshi** [comment]
All i can add on is anecdotal info from dumb console.log debugging:

all stream formats client.getInfo via web will give 403. with clientType.iOS and getBasicInfo(id, "iOS") will correctly decipher the correct stream urls. [freetube](https://github.com/FreeTubeApp/FreeTube) does some black magic that actually consolidates the streamFormat to a fewer number and all are playable as well. 

my guess/recommendation is to use the iOS clientType...

**Comment by gbarton** [comment]
Thank you for the reply!

So if I am just using the client_type.WEB then the getBasicInfo calls work fine and I determine what video formats and quality I want to dl.  Its the actual download that's failing every time for me.  

If I change the client to pretty much anything then I cannot get any info ones to work right.

The freetube is interesting, I'm reading here right now and am going to try porting over the IOS tricks and see if that lets downloads work again.  Thanks for the tip.

**Comment by gbarton** [comment]
I created the following silly test, does this work for anyone right now by chance?  Changing the client type will create 404 errors vs the 403 error I get with this.

```typescript
import { ClientType, Innertube, Utils as YTTools } from 'youtubei.js';

let done = false;
const id = '-xQQzi0IdLY';

async function run() {
  const yt = await Innertube.create({ client_type: ClientType.WEB, retrieve_player: true });
  console.log('stream created');
  const stream = await yt.download(id, {
    type: 'video',
    quality: 'best',
    format: 'mp4'
  });

  try {
    let chunks = 0;
  
    // need to wait on the write to ensure the file is completely ready
    for await (const chunk of YTTools.streamToIterable(stream)) {
      chunks += chunk.length;
      console.log(`${chunks} bytes`);
    }
    console.log(`completed ${chunks}`);
    done = true;
  } catch(err) {
    console.error(err);
    done = true;
  }

}

(async () => {
  console.log('running');
  await run();
  
  console.log('done');
})();
```

**Comment by lovegaoshi** [comment]
https://github.com/lovegaoshi/NoxPlayer/commit/24317ba57ab63d44e839ba2afadf482ae69bca62

this is what i have, b4 its 403 now it works

**Comment by gbarton** [comment]
bingo!  So there is a client on the download options as well I did not see.  That's why things 404 when I tried changing the client.  This works:

```typescript
import { ClientType, Innertube, Utils as YTTools } from 'youtubei.js';

let done = false;
const id = '-xQQzi0IdLY';

async function run() {
  const yt = await Innertube.create({
    client_type: ClientType.TV_EMBEDDED,
    generate_session_locally: false,
    enable_session_cache: false,
    retrieve_player: true
  });
  console.log('stream created');
  const stream = await yt.download(id, {
    type: 'video',
    quality: 'best',
    format: 'mp4',
    client: 'TV_EMBEDDED', // dont forget this if you change the client type!
  });

  try {
    let chunks = 0;
  
    // need to wait on the write to ensure the file is completely ready
    for await (const chunk of YTTools.streamToIterable(stream)) {
      chunks += chunk.length;
      console.log(`${chunks} bytes`);
    }
    console.log(`completed ${chunks}`);
    done = true;
  } catch(err) {
    console.error(err);
    done = true;
  }

}

(async () => {
  console.log('running');
  await run();
  
  console.log('done');
})();
```

Thank you lovegaoshi for the code that sparked the fix!  Interestingly there is no IOS option that I can pass in so I chose the tv option instead.

**Comment by yamadaMk12** [comment]
But why the video without sound ?
