### ISSUE TITLE
Unexpected toke invalid JSON when trying to reply to a comment

### ISSUE THREAD

**Issue by TechBroCode** [LuanRT/YouTube.js#742]
I got the following when trying to reply a comment :
SyntaxError: Unexpected token '�', "�u���p�"... is not valid JSON
    at JSON.parse (<anonymous>)
    at OAuth2.<anonymous> (C:\JetPlayWeb\node_modules\youtubei.js\bundle\node.cjs:17698:30)
    at Generator.next (<anonymous>)
    at fulfilled (C:\JetPlayWeb\node_modules\tslib\tslib.js:166:62)

I'm just stuck at this point. Below are my codes

innerYt.session.on('auth-pending', (data) => {
                        console.log(`From: Device => ${data.device_code}, Go to ${data.verification_url} in your browser and enter code ${data.user_code} to authenticate.`);
                    });

                    innerYt.session.once("auth", data => {
                        console.log(data.credentials);
                    });

                    await innerYt.session.signIn();
                    await innerYt.session.oauth.cacheCredentials();

const comments = await innerYt.getComments(videoId, "NEWEST_FIRST");
                    const contents = await comments.contents;
                    const reply = await contents[0].comment.reply("Hello");
res.json({
                        reply
                    });

**Comment by TechBroCode** [comment]
> I got the following when trying to reply a comment : SyntaxError: Unexpected token '�', "�u���p�"... is not valid JSON at JSON.parse () at OAuth2. (C:\JetPlayWeb\node_modules\youtubei.js\bundle\node.cjs:17698:30) at Generator.next () at fulfilled (C:\JetPlayWeb\node_modules\tslib\tslib.js:166:62)
> 
> I'm just stuck at this point. Below are my codes
> 
> innerYt.session.on('auth-pending', (data) => { console.log(`From: Device => ${data.device_code}, Go to ${data.verification_url} in your browser and enter code ${data.user_code} to authenticate.`); });
> 
> ```
>                 innerYt.session.once("auth", data => {
>                     console.log(data.credentials);
>                 });
> 
>                 await innerYt.session.signIn();
>                 await innerYt.session.oauth.cacheCredentials();
> ```
> 
> const comments = await innerYt.getComments(videoId, "NEWEST_FIRST"); const contents = await comments.contents; const reply = await contents[0].comment.reply("Hello"); res.json({ reply });

I just fixed the problem. The issue was that i wasn't initializing InnerYt very well
