### ISSUE TITLE
bleeding-edge Error when fetching home feed

### ISSUE THREAD

**Issue by walking-octopus** [LuanRT/YouTube.js#75]
## Current Behavior
I get this error when trying to get the home feed.

## Failure Information (for bugs)
```
Server error:  InnertubeError: ThumbnailOverlayEndorsement not found!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at Function.formatError (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:176:9)
    at Function.parse (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:149:18)
    at new Video (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/classes/Video.js:28:38)
    at Function.parse (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:162:26)
    at new RichItem (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/classes/RichItem.js:7:27)
    at Function.parse (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:145:28)
    at new RichGrid (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/classes/RichGrid.js:10:28)
    at Function.parse (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:162:26)
    at new Tab (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/classes/Tab.js:13:27)
    at Function.parse (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:145:28) {
  info: {
    text: { runs: [Array] },
    trackingParams: 'CIcEEKqIBhgGIhMIoN7wsbqw-AIVq0R6BR1YZgBR'
  },
  date: 2022-06-15T22:00:30.410Z,
  version: '1.4.3'
}
Server error:  InnertubeError: ThumbnailOverlayEndorsement not found!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at Function.formatError (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:176:9)
    at Function.parse (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:149:18)
    at new Video (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/classes/Video.js:28:38)
    at Function.parse (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:162:26)
    at new RichItem (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/classes/RichItem.js:7:27)
    at Function.parse (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:145:28)
    at new RichGrid (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/classes/RichGrid.js:10:28)
    at Function.parse (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:162:26)
    at new Tab (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/classes/Tab.js:13:27)
    at Function.parse (/home/stas/cathode-tube/build/x86_64-linux-gnu/app/install/yt-ws/node_modules/youtubei.js/lib/parser/contents/index.js:145:28) {
  info: {
    text: { runs: [Array] },
    trackingParams: 'CKIBEKqIBhgGIhMIoN7wsbqw-AIVq0R6BR1YZgBR'
  },
  date: 2022-06-15T22:00:30.413Z,
  version: '1.4.3'
}
```

**Comment by LuanRT** [comment]
I believe this is fixed now, feel free to reopen if it still persists.
