### ISSUE TITLE
10.5.0 [YOUTUBEJS][Parser]: InnertubeError: Something went wrong at ShortsLockupView!

### ISSUE THREAD

**Issue by ldenoue** [LuanRT/YouTube.js#780]
### Steps to reproduce

1. try with mE5_ziU5pWI
2. notice the parsing error

### Failure Logs

```shell
[YOUTUBEJS][Parser]: InnertubeError: Something went wrong at ShortsLockupView!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at ERROR_HANDLER (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14521:32)
    at parseItem (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14885:7)
    at Object.parseArray (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14901:22)
    at new ReelShelf (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:7069:33)
    at parseItem (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14881:22)
    at Object.parseArray (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14901:22)
    at new StructuredDescriptionContent (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:7101:33)
    at Object.parseItem (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14881:22)
    at new EngagementPanelSectionList (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:7124:35)
    at parseItem (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14881:22) {
  info: {
    stack: "TypeError: Cannot destructure property 'content' of 'data' as it is undefined.\n" +
      '    at Text.fromAttributed (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:5534:13)\n' +
      '    at new ShortsLockupView (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:12576:26)\n' +
      '    at parseItem (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14881:22)\n' +
      '    at Object.parseArray (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14901:22)\n' +
      '    at new ReelShelf (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:7069:33)\n' +
      '    at parseItem (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14881:22)\n' +
      '    at Object.parseArray (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14901:22)\n' +
      '    at new StructuredDescriptionContent (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:7101:33)\n' +
      '    at Object.parseItem (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:14881:22)\n' +
      '    at new EngagementPanelSectionList (/Users/ldenoue/git/appblit/node_modules/youtubei.js/bundle/node.cjs:7124:35)',
    classdata: '{\n' +
      '  "entityId": "shorts-shelf-item-mE5_ziU5pWI",\n' +
      '  "accessibilityText": "#chatgpt amps up its emotions in live demo #openai, 1.9K views - play Short",\n' +
      '  "thumbnail": {\n' +
      '    "sources": [\n' +
      '      {\n' +
      '        "url": "https://i.ytimg.com/vi/mE5_ziU5pWI/oardefault.jpg?sqp=-oaymwEkCJUDENAFSFqQAgHyq4qpAxMIARUAAAAAJQAAyEI9AICiQ3gB&rs=AOn4CLD3IHV4tzh8RxGqXIJ6XFk7ExemJA",\n' +
      '        "width": 405,\n' +
      '        "height": 720\n' +
      '      }\n' +
      '    ]\n' +
      '  },\n' +
      '  "onTap": {\n' +
      '    "innertubeCommand": {\n' +
      '      "clickTrackingParams": "CCQQh_YEGAAiEwiv-Lmtu42JAxVDMgYAHafJBEGaAQUIRRD4HQ==",\n' +
      '      "commandMetadata": {\n' +
      '        "webCommandMetadata": {\n' +
      '          "url": "/shorts/mE5_ziU5pWI",\n' +
      '          "webPageType": "WEB_PAGE_TYPE_SHORTS",\n' +
      '          "rootVe": 37414\n' +
      '        }\n' +
      '      },\n' +
      '      "reelWatchEndpoint": {\n' +
      '        "videoId": "mE5_ziU5pWI",\n' +
      '        "playerParams": "8AEByANFuAQfogYVAa6PwSbNs1je17WLp6K1bcvvPuYWkAcC",\n' +
      '        "thumbnail": {\n' +
      '          "thumbnails": [\n' +
      '            {\n' +
      '              "url": "https://i.ytimg.com/vi/mE5_ziU5pWI/frame0.jpg",\n' +
      '              "width": 1080,\n' +
      '              "height": 1920\n' +
      '            }\n' +
      '          ],\n' +
      '          "isOriginalAspectRatio": true\n' +
      '        },\n' +
      '        "overlay": {\n' +
      '          "reelPlayerOverlayRenderer": {\n' +
      '            "style": "REEL_PLAYER_OVERLAY_STYLE_SHORTS",\n' +
      '            "trackingParams": "CCUQsLUEIhMIr_i5rbuNiQMVQzIGAB2nyQRB",\n' +
      '            "reelPlayerNavigationModel": "REEL_PLAYER_NAVIGATION_MODEL_UNSPECIFIED"\n' +
      '          }\n' +
      '        },\n' +
      '        "params": "CB8wAg%3D%3D",\n' +
      '        "sequenceProvider": "REEL_WATCH_SEQUENCE_PROVIDER_RPC",\n' +
      '        "sequenceParams": "KjEKDQoLbUU1X3ppVTVwV0kKDQoLaEZaM1RERmVIR1kKDQoLTkVOaHliMnBIU1EQABgfUBloAYoBERoPCg0KC0RRYWNDQjl0RGF3kAEF",\n' +
      '        "loggingContext": {\n' +
      '          "vssLoggingContext": {\n' +
      '            "serializedContextData": "CgIIDA%3D%3D"\n' +
      '          },\n' +
      '          "qoeLoggingContext": {\n' +
      '            "serializedContextData": "CgIIDA%3D%3D"\n' +
      '          }\n' +
      '        },\n' +
      '        "ustreamerConfig": "CAwSGG1MdndaZU9qYzlpR3pxNnFMMkxGS1Q0PQ=="\n' +
      '      }\n' +
      '    }\n' +
      '  },\n' +
      '  "indexInCollection": 0,\n' +
      '  "overlayMetadata": {\n' +
      '    "secondaryText": {\n' +
      '      "content": "1.9K views"\n' +
      '    }\n' +
      '  },\n' +
      '  "loggingDirectives": {\n' +
      '    "trackingParams": "CCQQh_YEGAAiEwiv-Lmtu42JAxVDMgYAHafJBEE=",\n' +
      '    "visibility": {\n' +
      '      "types": "12"\n' +
      '    },\n' +
      '    "enableDisplayloggerExperiment": true\n' +
      '  }\n' +
      '}'
  },
  date: 2024-10-14T08:34:48.915Z,
  version: '10.5.0'
}
```

### Expected behavior

no error.

### Current behavior

error thrown

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by david8z** [comment]
Should be solved here: https://github.com/LuanRT/YouTube.js/pull/758

**Comment by ldenoue** [comment]
I confirm that the latest version fixed it. Thank you!
