### ISSUE TITLE
10.5.0 "Video is unplayable"

### ISSUE THREAD

**Issue by gbarton** [LuanRT/YouTube.js#784]
### Steps to reproduce

```
const yt = await Innertube.create({ ClientType.TV_EMBEDDED, retrieve_player: true });
const id = "yGr-hryViow";
const dlOpts = {
    type: "video"
    quality: "best"
    format: "mp4"
    contentLength: 69976591
    client: "TV_EMBEDDED"
};
const stream = await yt.download(id, dlObj);

```

### Failure Logs

```shell
err: {
      "type": "InnertubeError",
      "message": "Video is unplayable",
      "stack":
          Error: Video is unplayable
              at Object.download (/app/node_modules/youtubei.js/bundle/node.cjs:1822:11)
              at VideoInfo.download (/app/node_modules/youtubei.js/bundle/node.cjs:15374:32)
              at Innertube.download (/app/node_modules/youtubei.js/bundle/node.cjs:27515:17)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async /app/lib/utils/Utils.js:64:25
      "info": {
        "error_type": "UNPLAYABLE"
      },
      "date": "2024-10-24T13:46:48.320Z",
      "version": "10.5.0"
    }
```

### Expected behavior

download the video, worked fine till about 2 weeks ago.

### Current behavior

any video does this erroring, even ones I've downloaded before.

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by gbarton** [comment]
this is not working in 11.0.1 either.

**Comment by gbarton** [comment]
awesome that did it. I moved to the tv_embedded a while back to get around using android which was breaking.  Appreciate the response and all the fantastic work you all do!  Is the TV_EMBEDDED obsolete now?  Maybe it be worth having a client use/description page somewhere on what works and doesnt?
