### ISSUE TITLE
v11.0.1 Cannot set property duplex of #<Request> which has only a getter

### ISSUE THREAD

**Issue by ivan-pugach-sprinterra** [LuanRT/YouTube.js#813]
### Steps to reproduce

1. Implement integration with the FreeTubeApp
2. Open the page with the video that is integrated
3. Open the browser's console
<img width="1718" alt="Screenshot at Nov 21 22-19-37" src="https://github.com/user-attachments/assets/c9ee2c92-cdff-46d8-9c8a-863bf0e59312">
<img width="1501" alt="Screenshot at Nov 21 22-19-59" src="https://github.com/user-attachments/assets/d4ac4c58-d59e-4501-b2d9-583bfd1628a1">

### Failure Logs

```shell
index.0298021d.js:177 TypeError: Cannot set property duplex of #<Request> which has only a getter
    at lB.fetch (index.0298021d.js:177:92802)
    at lB.fetch (index.0298021d.js:5:13499)
    at NH.execute (index.0298021d.js:48:14484)
    at J3.getInfo (index.0298021d.js:48:108553)
    at ere (index.0298021d.js:177:93058)
```

### Expected behavior

Integrated video should show on the page

### Current behavior

Error in the console and video is not working

### Version

Edge

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by gowthamcbt** [comment]
![image](https://github.com/user-attachments/assets/541af9e6-0ed5-4e16-a48e-46feac4d31f2)


remove the line no 30 (input.duplex = 'half') and try again

**Comment by gmselvam1997** [comment]
![image](https://github.com/user-attachments/assets/8600d01e-2188-495e-b786-cd46c69d8e71)


remove the line no 30 (input.duplex ='half') and try again
